/**
 * Slack Integration — Phase 5
 * Operational alerting, governance escalations, Business Brain summaries.
 *
 * All messages flow through integration-runtime.ts.
 */

import { executeIntegrationAction, getIntegration, normalizeProviderResponse } from "../integration-runtime";

export type SlackAlertSeverity = "critical" | "warning" | "info" | "success";

export interface SlackAlertInput {
  orgId: string;
  agentType?: string;
  workflowJobId?: string;
  severity: SlackAlertSeverity;
  title: string;
  body: string;
  channel?: string;
  deduplicationKey?: string;
  actionUrl?: string;
  actionLabel?: string;
}

// Color map for Slack attachment colors
const SEVERITY_COLORS: Record<SlackAlertSeverity, string> = {
  critical: "#ef4444",
  warning: "#f59e0b",
  info: "#3b82f6",
  success: "#22c55e",
};

const SEVERITY_EMOJI: Record<SlackAlertSeverity, string> = {
  critical: "🚨",
  warning: "⚠️",
  info: "ℹ️",
  success: "✅",
};

// ─── Send Alert ───────────────────────────────────────────────────────────────

export async function slackSendAlert(input: SlackAlertInput): Promise<{ ok: boolean; ts?: string; error?: string }> {
  const result = await executeIntegrationAction(
    {
      orgId: input.orgId,
      integrationType: "slack",
      actionType: "send_alert",
      agentType: input.agentType ?? "workflow_agent",
      workflowJobId: input.workflowJobId,
      idempotencyKey: input.deduplicationKey,
      inputSummary: `[${input.severity.toUpperCase()}] ${input.title}`,
      payload: { severity: input.severity, title: input.title },
    },
    async () => {
      const integration = await getIntegration(input.orgId, "slack");
      if (!integration || integration.status !== "connected") {
        throw new Error("Slack integration not connected");
      }
      const creds = integration.encryptedCredentials as any ?? {};
      if (!creds.botToken && !creds.webhookUrl) {
        throw new Error("Slack credentials not configured");
      }

      const channel = input.channel ?? creds.defaultChannel ?? "#ai-ops";
      const emoji = SEVERITY_EMOJI[input.severity];
      const color = SEVERITY_COLORS[input.severity];

      const payload: any = {
        channel,
        text: `${emoji} *${input.title}*`,
        attachments: [
          {
            color,
            text: input.body,
            footer: `TrainEfficiency AI Ops · ${new Date().toISOString()}`,
            ...(input.actionUrl && input.actionLabel
              ? {
                  actions: [{
                    type: "button",
                    text: input.actionLabel,
                    url: input.actionUrl,
                  }],
                }
              : {}),
          },
        ],
      };

      if (creds.webhookUrl) {
        // Use incoming webhook
        const response = await fetch(creds.webhookUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });
        if (!response.ok) throw new Error(`Slack webhook failed: ${response.status}`);
        return normalizeProviderResponse({ ts: Date.now().toString() });
      } else {
        // Use Bot API
        const response = await fetch("https://slack.com/api/chat.postMessage", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${creds.botToken}`,
          },
          body: JSON.stringify(payload),
        });
        const data = await response.json() as any;
        if (!data.ok) throw new Error(`Slack API error: ${data.error}`);
        return normalizeProviderResponse({ ts: data.ts, channel: data.channel });
      }
    },
  );

  if (!result.ok) return { ok: false, error: result.error };
  return { ok: true, ts: result.data?.id as string };
}

// ─── Send Executive Summary ───────────────────────────────────────────────────

export async function slackSendExecutiveSummary(
  orgId: string,
  summary: string,
  metrics?: Record<string, string | number>,
): Promise<{ ok: boolean; error?: string }> {
  const blocks: any[] = [
    {
      type: "header",
      text: { type: "plain_text", text: "📊 Business Brain Daily Summary" },
    },
    {
      type: "section",
      text: { type: "mrkdwn", text: summary },
    },
  ];

  if (metrics && Object.keys(metrics).length > 0) {
    const fields = Object.entries(metrics)
      .slice(0, 10)
      .map(([key, val]) => ({ type: "mrkdwn", text: `*${key}*\n${val}` }));
    blocks.push({ type: "section", fields });
  }

  blocks.push({
    type: "context",
    elements: [{ type: "mrkdwn", text: `Generated by Atlas · ${new Date().toLocaleDateString()}` }],
  });

  return slackSendAlert({
    orgId,
    agentType: "executive_agent",
    severity: "info",
    title: "Business Brain Daily Summary",
    body: summary,
  });
}

// ─── Stuck-Job Alert ──────────────────────────────────────────────────────────

export async function slackAlertStuckJob(orgId: string, jobId: string, jobType: string, stuckMinutes: number): Promise<void> {
  await slackSendAlert({
    orgId,
    severity: "warning",
    title: "Stuck Workflow Job Detected",
    body: `Job \`${jobId}\` (type: \`${jobType}\`) has been running for ${stuckMinutes} minutes without completing. Check the Dead Letter Queue.`,
    deduplicationKey: `stuck-job-${jobId}`,
    actionUrl: "/admin/agent-ops",
    actionLabel: "View Dead Letter Queue",
  });
}

// ─── Governance Escalation ────────────────────────────────────────────────────

export async function slackAlertGovernanceEscalation(
  orgId: string,
  agentType: string,
  actionType: string,
  reason: string,
): Promise<void> {
  await slackSendAlert({
    orgId,
    agentType,
    severity: "critical",
    title: "Governance Escalation Required",
    body: `Agent *${agentType}* attempted action \`${actionType}\` which requires approval.\n\n_Reason: ${reason}_`,
    actionUrl: "/admin/agent-ops",
    actionLabel: "Review in Agent Ops",
  });
}

// ─── Emergency Pause Notification ────────────────────────────────────────────

export async function slackNotifyEmergencyPause(orgId: string, pausedBy: string): Promise<void> {
  await slackSendAlert({
    orgId,
    severity: "critical",
    title: "🛑 Emergency AI Pause Activated",
    body: `All AI agent operations have been paused by *${pausedBy}*. No autonomous actions will execute until the pause is lifted.`,
    deduplicationKey: `emergency-pause-${orgId}-${Date.now()}`,
  });
}

// ─── Connection Test ──────────────────────────────────────────────────────────

export async function testSlackConnection(orgId: string): Promise<{ ok: boolean; channel?: string; error?: string }> {
  try {
    const integration = await getIntegration(orgId, "slack");
    if (!integration) return { ok: false, error: "Not configured" };
    const creds = integration.encryptedCredentials as any ?? {};
    if (!creds.botToken && !creds.webhookUrl) return { ok: false, error: "No credentials" };
    return { ok: true, channel: creds.defaultChannel ?? "#ai-ops" };
  } catch (err: any) {
    return { ok: false, error: err.message };
  }
}
