import { useState, useMemo } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import {
  Mail, Search, CheckCircle, XCircle, RefreshCw, Filter, MinusCircle,
  Bot, Users, Send, Target, TrendingUp, Clock, Plus, Eye, Zap,
  PhoneOff, MessageSquare, Edit2, Trash2, ChevronDown, ChevronUp,
  Loader2, AlertCircle, DollarSign, Calendar, SkipForward, Settings2
} from "lucide-react";
import { format, parseISO, isAfter, isBefore, startOfDay, endOfDay } from "date-fns";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import type { CommunicationLog, TeamTrainingProspect, TeamTrainingOutreachDraft } from "@shared/schema";

// ─── Constants ────────────────────────────────────────────────────────────────
const TYPE_LABELS: Record<string, string> = {
  booking_confirmation: "Booking Confirmation",
  cancellation: "Cancellation",
  reschedule: "Reschedule",
  recurring: "Recurring",
  reminder: "Reminder",
  outreach: "Outreach",
};
const TYPE_COLORS: Record<string, string> = {
  booking_confirmation: "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300",
  cancellation: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300",
  reschedule: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300",
  recurring: "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300",
  reminder: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
  outreach: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
};
const STATUS_COLORS: Record<string, string> = {
  "New": "bg-blue-500/15 text-blue-700 dark:text-blue-400",
  "Needs Review": "bg-yellow-500/15 text-yellow-700 dark:text-yellow-400",
  "Approved": "bg-green-500/15 text-green-700 dark:text-green-400",
  "Contacted": "bg-purple-500/15 text-purple-700 dark:text-purple-400",
  "Replied": "bg-emerald-500/15 text-emerald-700 dark:text-emerald-400",
  "Not Interested": "bg-slate-500/15 text-slate-600 dark:text-slate-400",
  "Do Not Contact": "bg-red-500/15 text-red-700 dark:text-red-400",
};
const SPORTS = [
  "Football", "Soccer", "Basketball", "Baseball", "Volleyball", "Lacrosse",
  "Wrestling", "Cheer", "Swimming", "Track & Field", "Softball", "Martial Arts",
  "Tennis", "Cross Country", "Gymnastics", "Rowing",
];
const SPORTS_MULTISELECT = SPORTS;

type DraftWithProspect = TeamTrainingOutreachDraft & { prospect?: TeamTrainingProspect };

interface EmailAgentOverview {
  sentToday: number;
  dailyLimit: number;
  totalProspects: number;
  prospectsWithEmail: number;
  replied: number;
  interested: number;
  estimatedPipeline: number;
}
interface EmailPerformanceStats {
  sent: number;
  opened: number;
  clicked: number;
  replied: number;
  openRate: number;
  clickRate: number;
  replyRate: number;
  conversionRate: number;
  bestVariant: { id: string; name: string; performanceScore: number; timesUsed: number } | null;
}
interface EmailAgentSettings {
  enabled?: boolean;
  dailyLimit?: number;
  outreachRadius?: number;
  cooldownDays?: number;
  autoGenerateDrafts?: boolean;
  autoSend?: boolean;
  preferredSports?: string[];
  targetLevels?: string[];
  defaultEstimatedValue?: number;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function ConfidenceBar({ score }: { score: number }) {
  const color = score >= 75 ? "bg-green-500" : score >= 50 ? "bg-yellow-500" : "bg-red-400";
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-1.5 bg-muted rounded-full overflow-hidden">
        <div className={`h-full ${color} rounded-full`} style={{ width: `${score}%` }} />
      </div>
      <span className="text-xs text-muted-foreground w-8 text-right">{score}%</span>
    </div>
  );
}

// ─── Overview Tab ─────────────────────────────────────────────────────────────
function OverviewTab() {
  const { toast } = useToast();

  const { data: overview, isLoading: overviewLoading, refetch: refetchOverview } = useQuery<EmailAgentOverview>({
    queryKey: ["/api/email-agent/overview"],
  });
  const { data: queue, isLoading: queueLoading, refetch: refetchQueue } = useQuery<TeamTrainingProspect[]>({
    queryKey: ["/api/email-agent/queue"],
  });
  const { data: perf, isLoading: perfLoading } = useQuery<EmailPerformanceStats>({
    queryKey: ["/api/email-agent/performance"],
  });

  const buildQueueMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/email-agent/queue/build").then(r => r.json()),
    onSuccess: (data) => {
      toast({ title: "Queue built", description: `${data.count} prospects queued for today.` });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/queue"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const generateDraftMutation = useMutation({
    mutationFn: (prospectId: string) =>
      apiRequest("POST", `/api/admin/team-training/prospects/${prospectId}/generate-email`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Draft generated", description: "Check the Drafts tab to review." });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const dncMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/prospects/${id}/do-not-contact`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Marked Do Not Contact" });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/queue"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const sentToday = overview?.sentToday ?? 0;
  const dailyLimit = overview?.dailyLimit ?? 10;
  const limitReached = sentToday >= dailyLimit;

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
        <Card data-testid="card-emails-sent-today">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <Send className="h-4 w-4 text-primary" />
              <span className="text-xs text-muted-foreground">Sent Today</span>
            </div>
            {overviewLoading ? <Skeleton className="h-7 w-16" /> : (
              <p className="text-2xl font-bold" data-testid="text-sent-today">
                {sentToday} / {dailyLimit}
              </p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">Daily limit</p>
          </CardContent>
        </Card>
        <Card data-testid="card-prospect-list">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <Users className="h-4 w-4 text-blue-500" />
              <span className="text-xs text-muted-foreground">Prospects</span>
            </div>
            {overviewLoading ? <Skeleton className="h-7 w-16" /> : (
              <p className="text-2xl font-bold" data-testid="text-total-prospects">{overview?.totalProspects ?? 0}</p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">{overview?.prospectsWithEmail ?? 0} with email</p>
          </CardContent>
        </Card>
        <Card data-testid="card-replies">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <MessageSquare className="h-4 w-4 text-emerald-500" />
              <span className="text-xs text-muted-foreground">Replied</span>
            </div>
            {overviewLoading ? <Skeleton className="h-7 w-16" /> : (
              <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400" data-testid="text-replied">{overview?.replied ?? 0}</p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">Interested prospects</p>
          </CardContent>
        </Card>
        <Card data-testid="card-pipeline">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <DollarSign className="h-4 w-4 text-green-500" />
              <span className="text-xs text-muted-foreground">Est. Pipeline</span>
            </div>
            {overviewLoading ? <Skeleton className="h-7 w-16" /> : (
              <p className="text-2xl font-bold text-green-600 dark:text-green-400" data-testid="text-pipeline">
                ${((overview?.estimatedPipeline ?? 0)).toLocaleString()}
              </p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">Active prospects</p>
          </CardContent>
        </Card>
        <Card data-testid="card-queue-size">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <Target className="h-4 w-4 text-orange-500" />
              <span className="text-xs text-muted-foreground">Today's Queue</span>
            </div>
            {queueLoading ? <Skeleton className="h-7 w-16" /> : (
              <p className="text-2xl font-bold" data-testid="text-queue-size">{queue?.length ?? 0}</p>
            )}
            <p className="text-xs text-muted-foreground mt-0.5">Selected for today</p>
          </CardContent>
        </Card>
      </div>

      {/* Daily Limit Warning */}
      {limitReached && (
        <Card className="border-amber-200 bg-amber-50 dark:bg-amber-900/20 dark:border-amber-800">
          <CardContent className="pt-4 pb-4 flex items-center gap-3">
            <AlertCircle className="h-5 w-5 text-amber-600 dark:text-amber-400 shrink-0" />
            <p className="text-sm text-amber-800 dark:text-amber-300 font-medium" data-testid="text-daily-limit-reached">
              Daily outreach limit reached. {sentToday} / {dailyLimit} emails sent today.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Email Performance Section */}
      <div>
        <h2 className="text-base font-semibold mb-3 flex items-center gap-2" data-testid="heading-email-performance">
          <TrendingUp className="h-4 w-4 text-primary" />
          Email Performance
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
          <Card data-testid="card-open-rate">
            <CardContent className="pt-4 pb-4">
              <div className="flex items-center gap-2 mb-1">
                <Eye className="h-4 w-4 text-blue-500" />
                <span className="text-xs text-muted-foreground">Open Rate</span>
              </div>
              {perfLoading ? <Skeleton className="h-7 w-16" /> : (
                <p className="text-2xl font-bold text-blue-600 dark:text-blue-400" data-testid="text-open-rate">
                  {perf?.openRate ?? 0}%
                </p>
              )}
              <p className="text-xs text-muted-foreground mt-0.5">{perf?.opened ?? 0} of {perf?.sent ?? 0} sent</p>
            </CardContent>
          </Card>
          <Card data-testid="card-reply-rate">
            <CardContent className="pt-4 pb-4">
              <div className="flex items-center gap-2 mb-1">
                <MessageSquare className="h-4 w-4 text-emerald-500" />
                <span className="text-xs text-muted-foreground">Reply Rate</span>
              </div>
              {perfLoading ? <Skeleton className="h-7 w-16" /> : (
                <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400" data-testid="text-reply-rate">
                  {perf?.replyRate ?? 0}%
                </p>
              )}
              <p className="text-xs text-muted-foreground mt-0.5">{perf?.replied ?? 0} replies</p>
            </CardContent>
          </Card>
          <Card data-testid="card-conversion-rate">
            <CardContent className="pt-4 pb-4">
              <div className="flex items-center gap-2 mb-1">
                <CheckCircle className="h-4 w-4 text-green-500" />
                <span className="text-xs text-muted-foreground">Conversion Rate</span>
              </div>
              {perfLoading ? <Skeleton className="h-7 w-16" /> : (
                <p className="text-2xl font-bold text-green-600 dark:text-green-400" data-testid="text-conversion-rate">
                  {perf?.conversionRate ?? 0}%
                </p>
              )}
              <p className="text-xs text-muted-foreground mt-0.5">Replied or booked</p>
            </CardContent>
          </Card>
          <Card data-testid="card-best-variant">
            <CardContent className="pt-4 pb-4">
              <div className="flex items-center gap-2 mb-1">
                <Zap className="h-4 w-4 text-orange-500" />
                <span className="text-xs text-muted-foreground">Best Message</span>
              </div>
              {perfLoading ? <Skeleton className="h-7 w-28" /> : (
                <p className="text-sm font-bold truncate" data-testid="text-best-variant">
                  {perf?.bestVariant?.name ?? "—"}
                </p>
              )}
              <p className="text-xs text-muted-foreground mt-0.5">
                {perf?.bestVariant ? `Score: ${perf.bestVariant.performanceScore}` : "No variants yet"}
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Insight line */}
        {perf && perf.sent > 0 && (
          <Card className="border-primary/20 bg-primary/5 dark:bg-primary/10" data-testid="card-perf-insight">
            <CardContent className="pt-3 pb-3 flex items-start gap-3">
              <Bot className="h-4 w-4 text-primary mt-0.5 shrink-0" />
              <p className="text-sm text-foreground" data-testid="text-perf-insight">
                {perf.conversionRate > 0
                  ? `Your outreach is converting at ${perf.conversionRate}%. ${
                      perf.bestVariant
                        ? `Best results are coming from "${perf.bestVariant.name}" messages.`
                        : ""
                    } ${
                      perf.openRate > 30 && perf.replyRate < 5
                        ? "Opens are strong but replies are low — consider shorter, more direct messages."
                        : ""
                    }`
                  : `${perf.sent} email${perf.sent !== 1 ? "s" : ""} sent so far. Replies and opens will appear here as responses come in.`
                }
              </p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Today's Outreach Queue */}
      <div>
        <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
          <h2 className="text-base font-semibold" data-testid="heading-outreach-queue">Today's Outreach Queue</h2>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => { refetchOverview(); refetchQueue(); }}
              data-testid="button-refresh-queue"
            >
              <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
              Refresh
            </Button>
            <Button
              size="sm"
              onClick={() => buildQueueMutation.mutate()}
              disabled={buildQueueMutation.isPending || limitReached}
              data-testid="button-build-queue"
            >
              {buildQueueMutation.isPending ? <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> : <Zap className="h-3.5 w-3.5 mr-1.5" />}
              Build Queue
            </Button>
          </div>
        </div>

        {queueLoading ? (
          <div className="space-y-3">
            {[1, 2, 3].map(i => <Skeleton key={i} className="h-24 w-full" />)}
          </div>
        ) : !queue || queue.length === 0 ? (
          <Card>
            <CardContent className="py-10 text-center text-muted-foreground" data-testid="text-empty-queue">
              <Target className="h-8 w-8 mx-auto mb-2 opacity-30" />
              <p className="font-medium">No prospects in today's queue</p>
              <p className="text-sm mt-1">Click "Build Queue" to auto-select up to {dailyLimit} prospects</p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-3">
            {queue.map((prospect) => (
              <QueueProspectCard
                key={prospect.id}
                prospect={prospect}
                onGenerateDraft={() => generateDraftMutation.mutate(prospect.id)}
                onSkip={() => dncMutation.mutate(prospect.id)}
                generatingDraft={generateDraftMutation.isPending}
                limitReached={limitReached}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function QueueProspectCard({
  prospect,
  onGenerateDraft,
  onSkip,
  generatingDraft,
  limitReached,
}: {
  prospect: TeamTrainingProspect;
  onGenerateDraft: () => void;
  onSkip: () => void;
  generatingDraft: boolean;
  limitReached: boolean;
}) {
  const { toast } = useToast();
  const [showDraftDialog, setShowDraftDialog] = useState(false);

  const { data: drafts } = useQuery<TeamTrainingOutreachDraft[]>({
    queryKey: ["/api/admin/team-training/prospects", prospect.id, "drafts"],
    queryFn: () => fetch(`/api/admin/team-training/prospects/${prospect.id}/drafts`).then(r => r.json()),
  });
  const latestDraft = drafts?.[0];

  const sendMutation = useMutation({
    mutationFn: (draftId: string) => apiRequest("POST", `/api/admin/team-training/drafts/${draftId}/send`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Email sent!", description: `Outreach sent to ${prospect.contactEmail}` });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/queue"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects", prospect.id, "drafts"] });
    },
    onError: (e: any) => toast({ title: "Send failed", description: e.message, variant: "destructive" }),
  });

  const approveMutation = useMutation({
    mutationFn: (draftId: string) => apiRequest("POST", `/api/admin/team-training/drafts/${draftId}/approve`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Draft approved" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects", prospect.id, "drafts"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  return (
    <Card className="p-4" data-testid={`card-queue-prospect-${prospect.id}`}>
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-sm" data-testid={`text-queue-name-${prospect.id}`}>{prospect.prospectName}</span>
            <Badge className={`text-xs ${STATUS_COLORS[prospect.outreachStatus || "New"]}`}>{prospect.outreachStatus}</Badge>
            {prospect.sport && prospect.sport !== "unknown" && (
              <Badge variant="outline" className="text-xs">{prospect.sport}</Badge>
            )}
          </div>
          <div className="flex flex-wrap gap-3 mt-1 text-xs text-muted-foreground">
            {prospect.contactName && prospect.contactName !== "unknown" && (
              <span>{prospect.contactName}{prospect.contactRole && prospect.contactRole !== "unknown" ? ` · ${prospect.contactRole}` : ""}</span>
            )}
            {prospect.contactEmail && (
              <span className="font-mono" data-testid={`text-queue-email-${prospect.id}`}>{prospect.contactEmail}</span>
            )}
            {prospect.city && prospect.city !== "unknown" && (
              <span>{prospect.city}{prospect.state && prospect.state !== "unknown" ? `, ${prospect.state}` : ""}</span>
            )}
          </div>
          {typeof prospect.confidenceScore === "number" && (
            <div className="mt-2 max-w-xs">
              <ConfidenceBar score={prospect.confidenceScore} />
            </div>
          )}
          {prospect.estimatedValue && (
            <p className="text-xs text-muted-foreground mt-1">Est. value: <span className="font-medium text-foreground">${prospect.estimatedValue.toLocaleString()}</span></p>
          )}
        </div>
        <div className="flex flex-wrap gap-2 shrink-0">
          {latestDraft && (
            <Button size="sm" variant="outline" onClick={() => setShowDraftDialog(true)} data-testid={`button-view-draft-${prospect.id}`}>
              <Eye className="h-3.5 w-3.5 mr-1.5" />
              View Draft
            </Button>
          )}
          {!latestDraft && (
            <Button size="sm" variant="outline" onClick={onGenerateDraft} disabled={generatingDraft} data-testid={`button-gen-draft-${prospect.id}`}>
              {generatingDraft ? <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> : <Bot className="h-3.5 w-3.5 mr-1.5" />}
              Generate Draft
            </Button>
          )}
          {latestDraft && !latestDraft.sentAt && (
            <>
              {!latestDraft.approved && (
                <Button size="sm" variant="outline" onClick={() => approveMutation.mutate(latestDraft.id)} disabled={approveMutation.isPending} data-testid={`button-approve-${prospect.id}`}>
                  <CheckCircle className="h-3.5 w-3.5 mr-1.5" />
                  Approve
                </Button>
              )}
              {latestDraft.approved && (
                <Button size="sm" onClick={() => sendMutation.mutate(latestDraft.id)} disabled={sendMutation.isPending || limitReached} data-testid={`button-send-now-${prospect.id}`}>
                  {sendMutation.isPending ? <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> : <Send className="h-3.5 w-3.5 mr-1.5" />}
                  Send Now
                </Button>
              )}
            </>
          )}
          {latestDraft?.sentAt && (
            <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">Sent</Badge>
          )}
          <Button size="sm" variant="ghost" onClick={onSkip} className="text-muted-foreground hover:text-red-600" data-testid={`button-dnc-${prospect.id}`}>
            <PhoneOff className="h-3.5 w-3.5 mr-1.5" />
            DNC
          </Button>
        </div>
      </div>

      {/* Draft Preview Dialog */}
      {latestDraft && (
        <Dialog open={showDraftDialog} onOpenChange={setShowDraftDialog}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>Email Draft — {prospect.prospectName}</DialogTitle>
            </DialogHeader>
            <div className="space-y-3">
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Subject</p>
                <p className="font-medium" data-testid="text-draft-subject">{latestDraft.subject}</p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Body</p>
                <div className="bg-muted/50 rounded-lg p-3 text-sm whitespace-pre-wrap max-h-64 overflow-y-auto" data-testid="text-draft-body">
                  {latestDraft.body}
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowDraftDialog(false)} data-testid="button-close-draft">Close</Button>
              {!latestDraft.approved && (
                <Button onClick={() => { approveMutation.mutate(latestDraft.id); setShowDraftDialog(false); }} disabled={approveMutation.isPending} data-testid="button-approve-from-dialog">
                  <CheckCircle className="h-4 w-4 mr-1.5" />
                  Approve Draft
                </Button>
              )}
              {latestDraft.approved && !latestDraft.sentAt && (
                <Button onClick={() => { sendMutation.mutate(latestDraft.id); setShowDraftDialog(false); }} disabled={sendMutation.isPending} data-testid="button-send-from-dialog">
                  <Send className="h-4 w-4 mr-1.5" />
                  Send Now
                </Button>
              )}
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </Card>
  );
}

// ─── Prospects Tab ────────────────────────────────────────────────────────────
function ProspectsTab() {
  const { toast } = useToast();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [sportFilter, setSportFilter] = useState("all");
  const [emailFilter, setEmailFilter] = useState("all");
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [editProspect, setEditProspect] = useState<TeamTrainingProspect | null>(null);
  const [researchSport, setResearchSport] = useState("");

  const { data: prospects, isLoading, refetch } = useQuery<TeamTrainingProspect[]>({
    queryKey: ["/api/admin/team-training/prospects"],
  });

  const filtered = useMemo(() => {
    if (!prospects) return [];
    return prospects.filter(p => {
      if (statusFilter !== "all" && p.outreachStatus !== statusFilter) return false;
      if (sportFilter !== "all" && p.sport?.toLowerCase() !== sportFilter.toLowerCase()) return false;
      if (emailFilter === "has_email" && !p.contactEmail) return false;
      if (emailFilter === "no_email" && p.contactEmail) return false;
      if (search.trim()) {
        const q = search.toLowerCase();
        return (
          p.prospectName.toLowerCase().includes(q) ||
          (p.contactEmail || "").toLowerCase().includes(q) ||
          (p.city || "").toLowerCase().includes(q) ||
          (p.sport || "").toLowerCase().includes(q)
        );
      }
      return true;
    });
  }, [prospects, statusFilter, sportFilter, emailFilter, search]);

  const researchMutation = useMutation({
    mutationFn: (sport?: string) => apiRequest("POST", "/api/admin/team-training/research", { sport: sport || undefined, limit: 10 }).then(r => r.json()),
    onSuccess: (data) => {
      toast({ title: "Research complete", description: `Found ${data.count} prospects.` });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const generateDraftMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/prospects/${id}/generate-email`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Draft generated", description: "Review it in the Drafts tab." });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const dncMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/prospects/${id}/do-not-contact`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Marked Do Not Contact" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/team-training/prospects/${id}`).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Deleted" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  return (
    <div className="space-y-4">
      {/* Action Bar */}
      <div className="flex flex-wrap gap-2 items-center justify-between">
        <div className="flex flex-wrap gap-2">
          <Button
            onClick={() => researchMutation.mutate(researchSport || undefined)}
            disabled={researchMutation.isPending}
            data-testid="button-find-prospects"
          >
            {researchMutation.isPending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Target className="h-4 w-4 mr-2" />}
            Find Team Prospects
          </Button>
          <Select value={researchSport} onValueChange={setResearchSport}>
            <SelectTrigger className="w-36 h-9" data-testid="select-research-sport">
              <SelectValue placeholder="Any sport" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="">Any sport</SelectItem>
              {SPORTS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => refetch()} data-testid="button-refresh-prospects">
            <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
            Refresh
          </Button>
          <Button variant="outline" size="sm" onClick={() => setShowAddDialog(true)} data-testid="button-add-prospect">
            <Plus className="h-3.5 w-3.5 mr-1.5" />
            Add Prospect
          </Button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        <div className="relative flex-1 min-w-48">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input
            placeholder="Search prospects..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="pl-8 h-9"
            data-testid="input-prospect-search"
          />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-36 h-9" data-testid="select-prospect-status">
            <SelectValue placeholder="All statuses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            {Object.keys(STATUS_COLORS).map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={sportFilter} onValueChange={setSportFilter}>
          <SelectTrigger className="w-32 h-9" data-testid="select-prospect-sport">
            <SelectValue placeholder="All sports" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All sports</SelectItem>
            {SPORTS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={emailFilter} onValueChange={setEmailFilter}>
          <SelectTrigger className="w-32 h-9" data-testid="select-email-filter">
            <SelectValue placeholder="Email" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Any</SelectItem>
            <SelectItem value="has_email">Has Email</SelectItem>
            <SelectItem value="no_email">No Email</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Progress banner from research */}
      {researchMutation.isPending && (
        <Card className="border-primary/20 bg-primary/5">
          <CardContent className="py-3 flex items-center gap-3">
            <Loader2 className="h-4 w-4 animate-spin text-primary" />
            <span className="text-sm">Researching local athletic teams. This may take 30–60 seconds...</span>
          </CardContent>
        </Card>
      )}

      {/* Prospect List */}
      {isLoading ? (
        <div className="space-y-3">{[1,2,3,4].map(i => <Skeleton key={i} className="h-28 w-full" />)}</div>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground" data-testid="text-no-prospects">
            <Users className="h-8 w-8 mx-auto mb-2 opacity-30" />
            <p className="font-medium">{prospects?.length === 0 ? "No prospects yet" : "No prospects match your filters"}</p>
            {prospects?.length === 0 && (
              <p className="text-sm mt-1">Click "Find Team Prospects" to auto-discover local athletic teams</p>
            )}
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          <p className="text-xs text-muted-foreground">{filtered.length} of {prospects?.length} prospects</p>
          {filtered.map(p => (
            <ProspectCard
              key={p.id}
              prospect={p}
              onGenerateDraft={() => generateDraftMutation.mutate(p.id)}
              onEdit={() => setEditProspect(p)}
              onDnc={() => dncMutation.mutate(p.id)}
              onDelete={() => deleteMutation.mutate(p.id)}
            />
          ))}
        </div>
      )}

      <AddProspectDialog open={showAddDialog} onClose={() => setShowAddDialog(false)} />
      {editProspect && (
        <AddProspectDialog
          open={!!editProspect}
          onClose={() => setEditProspect(null)}
          prospect={editProspect}
        />
      )}
    </div>
  );
}

function ProspectCard({
  prospect,
  onGenerateDraft,
  onEdit,
  onDnc,
  onDelete,
}: {
  prospect: TeamTrainingProspect;
  onGenerateDraft: () => void;
  onEdit: () => void;
  onDnc: () => void;
  onDelete: () => void;
}) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className="p-4" data-testid={`card-prospect-${prospect.id}`}>
      <div className="flex items-start justify-between gap-2 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-sm" data-testid={`text-prospect-name-${prospect.id}`}>{prospect.prospectName}</span>
            <Badge className={`text-xs ${STATUS_COLORS[prospect.outreachStatus || "New"]}`} data-testid={`badge-prospect-status-${prospect.id}`}>{prospect.outreachStatus}</Badge>
            {prospect.sport && prospect.sport !== "unknown" && (
              <Badge variant="outline" className="text-xs">{prospect.sport}</Badge>
            )}
          </div>
          <div className="flex flex-wrap gap-3 mt-1 text-xs text-muted-foreground">
            <span>{prospect.organizationType}</span>
            {prospect.city && prospect.city !== "unknown" && <span>{prospect.city}{prospect.state && prospect.state !== "unknown" ? `, ${prospect.state}` : ""}</span>}
            {prospect.contactEmail ? (
              <span className="font-mono text-foreground" data-testid={`text-prospect-email-${prospect.id}`}>{prospect.contactEmail}</span>
            ) : (
              <span className="text-amber-600 dark:text-amber-400">No email</span>
            )}
          </div>
          {typeof prospect.confidenceScore === "number" && (
            <div className="mt-2 max-w-xs"><ConfidenceBar score={prospect.confidenceScore} /></div>
          )}
        </div>
        <div className="flex flex-wrap gap-1.5 shrink-0">
          {prospect.contactEmail && prospect.outreachStatus !== "Do Not Contact" && (
            <Button size="sm" variant="outline" className="h-7 text-xs" onClick={onGenerateDraft} data-testid={`button-gen-draft-prospect-${prospect.id}`}>
              <Bot className="h-3 w-3 mr-1" />Draft
            </Button>
          )}
          <Button size="sm" variant="outline" className="h-7 text-xs" onClick={onEdit} data-testid={`button-edit-prospect-${prospect.id}`}>
            <Edit2 className="h-3 w-3 mr-1" />Edit
          </Button>
          {prospect.outreachStatus !== "Do Not Contact" && (
            <Button size="sm" variant="ghost" className="h-7 text-xs text-muted-foreground hover:text-red-600" onClick={onDnc} data-testid={`button-dnc-prospect-${prospect.id}`}>
              <PhoneOff className="h-3 w-3 mr-1" />DNC
            </Button>
          )}
          <Button size="sm" variant="ghost" className="h-7 text-xs text-muted-foreground hover:text-destructive" onClick={onDelete} data-testid={`button-delete-prospect-${prospect.id}`}>
            <Trash2 className="h-3 w-3" />
          </Button>
          <Button size="sm" variant="ghost" className="h-7 text-xs text-muted-foreground" onClick={() => setExpanded(e => !e)} data-testid={`button-expand-prospect-${prospect.id}`}>
            {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
          </Button>
        </div>
      </div>
      {expanded && (
        <div className="mt-3 pt-3 border-t text-sm space-y-1">
          {prospect.contactName && prospect.contactName !== "unknown" && <p><span className="text-muted-foreground">Contact:</span> {prospect.contactName}{prospect.contactRole && prospect.contactRole !== "unknown" ? ` (${prospect.contactRole})` : ""}</p>}
          {prospect.contactPhone && <p><span className="text-muted-foreground">Phone:</span> {prospect.contactPhone}</p>}
          {prospect.websiteUrl && <p><span className="text-muted-foreground">Website:</span> <a href={prospect.websiteUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">{prospect.websiteUrl}</a></p>}
          {prospect.notes && prospect.notes !== "" && <p><span className="text-muted-foreground">Notes:</span> {prospect.notes}</p>}
          {prospect.lastContactedAt && <p><span className="text-muted-foreground">Last contacted:</span> {format(new Date(prospect.lastContactedAt), "MMM d, yyyy")}</p>}
        </div>
      )}
    </Card>
  );
}

function AddProspectDialog({ open, onClose, prospect }: { open: boolean; onClose: () => void; prospect?: TeamTrainingProspect }) {
  const { toast } = useToast();
  const [form, setForm] = useState({
    prospectName: prospect?.prospectName ?? "",
    sport: prospect?.sport ?? "",
    organizationType: prospect?.organizationType ?? "",
    contactName: prospect?.contactName ?? "",
    contactEmail: prospect?.contactEmail ?? "",
    contactPhone: prospect?.contactPhone ?? "",
    city: prospect?.city ?? "",
    state: prospect?.state ?? "",
    websiteUrl: prospect?.websiteUrl ?? "",
    notes: prospect?.notes ?? "",
    estimatedValue: prospect?.estimatedValue?.toString() ?? "",
  });

  const saveMutation = useMutation({
    mutationFn: () => {
      const body = {
        ...form,
        estimatedValue: form.estimatedValue ? parseInt(form.estimatedValue) : null,
        confidenceScore: 75,
      };
      if (prospect) {
        return apiRequest("PATCH", `/api/admin/team-training/prospects/${prospect.id}`, body).then(r => r.json());
      }
      return apiRequest("POST", "/api/admin/team-training/prospects", body).then(r => r.json());
    },
    onSuccess: () => {
      toast({ title: prospect ? "Prospect updated" : "Prospect added" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/prospects"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
      onClose();
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const set = (k: string, v: string) => setForm(f => ({ ...f, [k]: v }));

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{prospect ? "Edit Prospect" : "Add Prospect"}</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div>
            <Label htmlFor="prospectName">Team / School / Org Name *</Label>
            <Input id="prospectName" value={form.prospectName} onChange={e => set("prospectName", e.target.value)} placeholder="e.g. Westside FC Youth" className="mt-1" data-testid="input-prospect-name" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="sport">Sport</Label>
              <Select value={form.sport} onValueChange={v => set("sport", v)}>
                <SelectTrigger className="mt-1" data-testid="select-prospect-sport-add">
                  <SelectValue placeholder="Select sport" />
                </SelectTrigger>
                <SelectContent>
                  {SPORTS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="orgType">Org Type</Label>
              <Input id="orgType" value={form.organizationType} onChange={e => set("organizationType", e.target.value)} placeholder="e.g. Club Team" className="mt-1" data-testid="input-prospect-orgtype" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="contactName">Contact Name</Label>
              <Input id="contactName" value={form.contactName} onChange={e => set("contactName", e.target.value)} placeholder="Coach Smith" className="mt-1" data-testid="input-prospect-contact-name" />
            </div>
            <div>
              <Label htmlFor="contactEmail">Contact Email</Label>
              <Input id="contactEmail" type="email" value={form.contactEmail} onChange={e => set("contactEmail", e.target.value)} placeholder="coach@team.com" className="mt-1" data-testid="input-prospect-contact-email" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="city">City</Label>
              <Input id="city" value={form.city} onChange={e => set("city", e.target.value)} placeholder="Springfield" className="mt-1" data-testid="input-prospect-city" />
            </div>
            <div>
              <Label htmlFor="state">State</Label>
              <Input id="state" value={form.state} onChange={e => set("state", e.target.value)} placeholder="OH" className="mt-1" data-testid="input-prospect-state" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="website">Website</Label>
              <Input id="website" value={form.websiteUrl} onChange={e => set("websiteUrl", e.target.value)} placeholder="https://..." className="mt-1" data-testid="input-prospect-website" />
            </div>
            <div>
              <Label htmlFor="estimatedValue">Est. Value ($)</Label>
              <Input id="estimatedValue" type="number" value={form.estimatedValue} onChange={e => set("estimatedValue", e.target.value)} placeholder="2500" className="mt-1" data-testid="input-prospect-value" />
            </div>
          </div>
          <div>
            <Label htmlFor="notes">Notes</Label>
            <Textarea id="notes" value={form.notes} onChange={e => set("notes", e.target.value)} placeholder="Any relevant context..." rows={2} className="mt-1" data-testid="input-prospect-notes" />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose} data-testid="button-cancel-prospect">Cancel</Button>
          <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending || !form.prospectName} data-testid="button-save-prospect">
            {saveMutation.isPending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
            {prospect ? "Save Changes" : "Add Prospect"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Drafts Tab ───────────────────────────────────────────────────────────────
function DraftsTab() {
  const { toast } = useToast();
  const [editDraft, setEditDraft] = useState<DraftWithProspect | null>(null);

  const { data: drafts, isLoading, refetch } = useQuery<DraftWithProspect[]>({
    queryKey: ["/api/admin/team-training/drafts"],
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/drafts/${id}/approve`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Draft approved" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const sendMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/drafts/${id}/send`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Email sent!" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Send failed", description: e.message, variant: "destructive" }),
  });

  const updateDraftMutation = useMutation({
    mutationFn: ({ id, subject, body }: { id: string; subject: string; body: string }) =>
      apiRequest("PATCH", `/api/admin/team-training/drafts/${id}`, { subject, body }).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Draft saved" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
      setEditDraft(null);
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const pending = drafts?.filter(d => !d.sentAt) ?? [];
  const sent = drafts?.filter(d => !!d.sentAt) ?? [];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-sm font-semibold">AI-Generated Drafts</h2>
          <p className="text-xs text-muted-foreground">{pending.length} pending approval · {sent.length} sent</p>
        </div>
        <Button variant="outline" size="sm" onClick={() => refetch()} data-testid="button-refresh-drafts">
          <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
          Refresh
        </Button>
      </div>

      {isLoading ? (
        <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-32 w-full" />)}</div>
      ) : pending.length === 0 && sent.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground" data-testid="text-no-drafts">
            <Mail className="h-8 w-8 mx-auto mb-2 opacity-30" />
            <p className="font-medium">No drafts yet</p>
            <p className="text-sm mt-1">Generate drafts from the Prospects tab or the Overview queue</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {pending.map(draft => (
            <DraftCard
              key={draft.id}
              draft={draft}
              onApprove={() => approveMutation.mutate(draft.id)}
              onSend={() => sendMutation.mutate(draft.id)}
              onEdit={() => setEditDraft(draft)}
              approving={approveMutation.isPending}
              sending={sendMutation.isPending}
            />
          ))}
          {sent.length > 0 && (
            <>
              <p className="text-xs font-medium text-muted-foreground pt-2">Sent</p>
              {sent.map(draft => (
                <DraftCard key={draft.id} draft={draft} sent />
              ))}
            </>
          )}
        </div>
      )}

      {editDraft && (
        <EditDraftDialog
          draft={editDraft}
          onClose={() => setEditDraft(null)}
          onSave={(subject, body) => updateDraftMutation.mutate({ id: editDraft.id, subject, body })}
          saving={updateDraftMutation.isPending}
        />
      )}
    </div>
  );
}

function DraftCard({
  draft,
  onApprove,
  onSend,
  onEdit,
  approving,
  sending,
  sent,
}: {
  draft: DraftWithProspect;
  onApprove?: () => void;
  onSend?: () => void;
  onEdit?: () => void;
  approving?: boolean;
  sending?: boolean;
  sent?: boolean;
}) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className={`p-4 ${sent ? "opacity-70" : ""}`} data-testid={`card-draft-${draft.id}`}>
      <div className="flex items-start justify-between gap-2 flex-wrap">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium text-sm truncate" data-testid={`text-draft-prospect-${draft.id}`}>
              {draft.prospect?.prospectName || "Unknown Prospect"}
            </span>
            {draft.sentAt ? (
              <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300 text-xs">Sent</Badge>
            ) : draft.approved ? (
              <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300 text-xs">Approved</Badge>
            ) : (
              <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300 text-xs">Pending Review</Badge>
            )}
          </div>
          <p className="text-xs text-muted-foreground mt-0.5 truncate" data-testid={`text-draft-subject-${draft.id}`}>Subject: {draft.subject}</p>
          {draft.sentAt && (
            <p className="text-xs text-muted-foreground mt-0.5">Sent {format(new Date(draft.sentAt), "MMM d, yyyy h:mm a")}</p>
          )}
        </div>
        {!sent && (
          <div className="flex gap-1.5 shrink-0 flex-wrap">
            <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setExpanded(e => !e)} data-testid={`button-expand-draft-${draft.id}`}>
              {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5 mr-1" />}
              {!expanded && "Preview"}
            </Button>
            <Button size="sm" variant="outline" className="h-7 text-xs" onClick={onEdit} data-testid={`button-edit-draft-${draft.id}`}>
              <Edit2 className="h-3 w-3 mr-1" />Edit
            </Button>
            {!draft.approved && (
              <Button size="sm" variant="outline" className="h-7 text-xs" onClick={onApprove} disabled={approving} data-testid={`button-approve-draft-${draft.id}`}>
                <CheckCircle className="h-3 w-3 mr-1" />Approve
              </Button>
            )}
            {draft.approved && !draft.sentAt && (
              <Button size="sm" className="h-7 text-xs" onClick={onSend} disabled={sending} data-testid={`button-send-draft-${draft.id}`}>
                {sending ? <Loader2 className="h-3 w-3 mr-1 animate-spin" /> : <Send className="h-3 w-3 mr-1" />}Send
              </Button>
            )}
          </div>
        )}
      </div>
      {expanded && (
        <div className="mt-3 pt-3 border-t">
          <div className="bg-muted/50 rounded p-3 text-xs whitespace-pre-wrap max-h-48 overflow-y-auto" data-testid={`text-draft-body-${draft.id}`}>
            {draft.body}
          </div>
        </div>
      )}
    </Card>
  );
}

function EditDraftDialog({
  draft,
  onClose,
  onSave,
  saving,
}: {
  draft: DraftWithProspect;
  onClose: () => void;
  onSave: (subject: string, body: string) => void;
  saving: boolean;
}) {
  const [subject, setSubject] = useState(draft.subject);
  const [body, setBody] = useState(draft.body);

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Edit Draft — {draft.prospect?.prospectName}</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div>
            <Label>Subject</Label>
            <Input value={subject} onChange={e => setSubject(e.target.value)} className="mt-1" data-testid="input-edit-subject" />
          </div>
          <div>
            <Label>Body</Label>
            <Textarea value={body} onChange={e => setBody(e.target.value)} rows={12} className="mt-1 font-mono text-sm" data-testid="input-edit-body" />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose} data-testid="button-cancel-edit">Cancel</Button>
          <Button onClick={() => onSave(subject, body)} disabled={saving} data-testid="button-save-draft-edit">
            {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Sent Tab ─────────────────────────────────────────────────────────────────
function SentTab() {
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const { toast } = useToast();

  const { data: logs, isLoading, refetch, isFetching } = useQuery<CommunicationLog[]>({
    queryKey: ["/api/communication-logs"],
  });

  const { data: sentDrafts, isLoading: draftsLoading } = useQuery<DraftWithProspect[]>({
    queryKey: ["/api/admin/team-training/drafts"],
  });

  const markRepliedMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/prospects/${id}/mark-replied`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Marked as replied" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const dncMutation = useMutation({
    mutationFn: (id: string) => apiRequest("POST", `/api/admin/team-training/prospects/${id}/do-not-contact`, {}).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Marked Do Not Contact" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const filteredLogs = useMemo(() => {
    if (!logs) return [];
    return logs.filter((log) => {
      if (typeFilter !== "all" && log.type !== typeFilter) return false;
      if (statusFilter !== "all" && log.status !== statusFilter) return false;
      if (search.trim()) {
        const q = search.toLowerCase();
        if (!(log.recipientEmail || "").toLowerCase().includes(q) && !(log.subject || "").toLowerCase().includes(q)) return false;
      }
      if (dateFrom) {
        const from = startOfDay(parseISO(dateFrom));
        const sentAt = log.sentAt ? parseISO(log.sentAt as unknown as string) : null;
        if (!sentAt || isBefore(sentAt, from)) return false;
      }
      if (dateTo) {
        const to = endOfDay(parseISO(dateTo));
        const sentAt = log.sentAt ? parseISO(log.sentAt as unknown as string) : null;
        if (!sentAt || isAfter(sentAt, to)) return false;
      }
      return true;
    });
  }, [logs, typeFilter, statusFilter, search, dateFrom, dateTo]);

  const outreachDraftsSent = sentDrafts?.filter(d => !!d.sentAt) ?? [];

  const clearFilters = () => { setSearch(""); setTypeFilter("all"); setStatusFilter("all"); setDateFrom(""); setDateTo(""); };
  const hasFilters = search || typeFilter !== "all" || statusFilter !== "all" || dateFrom || dateTo;

  return (
    <div className="space-y-5">
      {/* Outreach Sent */}
      {outreachDraftsSent.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold mb-3">Team Outreach Emails Sent</h3>
          <div className="space-y-3">
            {outreachDraftsSent.map(draft => (
              <Card key={draft.id} className="p-4" data-testid={`card-sent-outreach-${draft.id}`}>
                <div className="flex items-start justify-between gap-2 flex-wrap">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-medium text-sm">{draft.prospect?.prospectName || "Unknown"}</span>
                      {draft.prospect?.sport && draft.prospect.sport !== "unknown" && (
                        <Badge variant="outline" className="text-xs">{draft.prospect.sport}</Badge>
                      )}
                      <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300 text-xs">
                        <CheckCircle className="h-3 w-3 mr-1" />Sent
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">{draft.subject}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      To: <span className="font-mono">{draft.prospect?.contactEmail || "—"}</span>
                      {draft.sentAt && ` · ${format(new Date(draft.sentAt), "MMM d, yyyy h:mm a")}`}
                    </p>
                    {draft.prospect?.estimatedValue && (
                      <p className="text-xs text-muted-foreground mt-0.5">Est. value: ${draft.prospect.estimatedValue.toLocaleString()}</p>
                    )}
                  </div>
                  {draft.prospect && (
                    <div className="flex gap-1.5 flex-wrap shrink-0">
                      <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => markRepliedMutation.mutate(draft.prospect!.id)} data-testid={`button-mark-replied-${draft.id}`}>
                        <MessageSquare className="h-3 w-3 mr-1" />Replied
                      </Button>
                      <Button size="sm" variant="ghost" className="h-7 text-xs text-muted-foreground hover:text-red-600" onClick={() => dncMutation.mutate(draft.prospect!.id)} data-testid={`button-sent-dnc-${draft.id}`}>
                        <PhoneOff className="h-3 w-3 mr-1" />DNC
                      </Button>
                    </div>
                  )}
                </div>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* System Email Logs */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-semibold">All System Emails</h3>
          <Button variant="outline" size="sm" onClick={() => refetch()} disabled={isFetching} data-testid="button-refresh-logs">
            <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${isFetching ? "animate-spin" : ""}`} />
            Refresh
          </Button>
        </div>

        {/* Filters */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 mb-3">
          <div className="relative sm:col-span-2">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
            <Input placeholder="Search email or subject..." value={search} onChange={e => setSearch(e.target.value)} className="pl-8 h-9" data-testid="input-sent-search" />
          </div>
          <Select value={typeFilter} onValueChange={setTypeFilter}>
            <SelectTrigger className="h-9" data-testid="select-sent-type">
              <SelectValue placeholder="All types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All types</SelectItem>
              {Object.entries(TYPE_LABELS).map(([k, v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="h-9" data-testid="select-sent-status">
              <SelectValue placeholder="All statuses" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All statuses</SelectItem>
              <SelectItem value="sent">Sent</SelectItem>
              <SelectItem value="failed">Failed</SelectItem>
              <SelectItem value="skipped">Skipped</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="flex gap-2 flex-wrap mb-3">
          <Input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} className="h-9 w-40 text-sm" data-testid="input-sent-from" />
          <Input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} className="h-9 w-40 text-sm" data-testid="input-sent-to" />
          {hasFilters && <Button variant="ghost" size="sm" onClick={clearFilters} data-testid="button-sent-clear">Clear</Button>}
        </div>

        <Card>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              {isLoading ? (
                <div className="p-4 space-y-3">{[1,2,3,4,5].map(i => <Skeleton key={i} className="h-10 w-full" />)}</div>
              ) : filteredLogs.length === 0 ? (
                <div className="py-10 text-center text-muted-foreground" data-testid="text-no-logs">
                  <Mail className="h-8 w-8 mx-auto mb-2 opacity-30" />
                  <p className="font-medium">No emails found</p>
                  <p className="text-sm mt-1">{hasFilters ? "Try adjusting your filters" : "Emails will appear here once sent"}</p>
                </div>
              ) : (
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b bg-muted/50">
                      <th className="text-left px-4 py-2.5 font-medium text-muted-foreground text-xs">Sent At</th>
                      <th className="text-left px-4 py-2.5 font-medium text-muted-foreground text-xs">Type</th>
                      <th className="text-left px-4 py-2.5 font-medium text-muted-foreground text-xs">Recipient</th>
                      <th className="text-left px-4 py-2.5 font-medium text-muted-foreground text-xs">Subject</th>
                      <th className="text-left px-4 py-2.5 font-medium text-muted-foreground text-xs">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredLogs.map((log, idx) => (
                      <tr key={log.id} className={`border-b last:border-0 hover:bg-muted/30 ${idx % 2 === 0 ? "" : "bg-muted/10"}`} data-testid={`row-log-${log.id}`}>
                        <td className="px-4 py-2.5 whitespace-nowrap text-xs text-muted-foreground">
                          {log.sentAt ? format(parseISO(log.sentAt as unknown as string), "MMM d, yyyy h:mm a") : "—"}
                        </td>
                        <td className="px-4 py-2.5 whitespace-nowrap">
                          <span className={`inline-flex items-center px-1.5 py-0.5 rounded-full text-xs font-medium ${TYPE_COLORS[log.type] ?? "bg-muted text-muted-foreground"}`}>{TYPE_LABELS[log.type] ?? log.type}</span>
                        </td>
                        <td className="px-4 py-2.5 text-xs">{log.recipientEmail}</td>
                        <td className="px-4 py-2.5 max-w-[200px] truncate text-xs" title={log.subject || ""}>{log.subject || "—"}</td>
                        <td className="px-4 py-2.5 whitespace-nowrap">
                          {log.status === "sent" ? (
                            <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300 text-xs border-0"><CheckCircle className="h-2.5 w-2.5 mr-1" />Sent</Badge>
                          ) : log.status === "skipped" ? (
                            <Badge className="bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300 text-xs border-0"><MinusCircle className="h-2.5 w-2.5 mr-1" />Skipped</Badge>
                          ) : (
                            <Badge className="bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300 text-xs border-0"><XCircle className="h-2.5 w-2.5 mr-1" />Failed</Badge>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
            {!isLoading && filteredLogs.length > 0 && (
              <div className="px-4 py-2 border-t text-xs text-muted-foreground">
                {filteredLogs.length} of {logs?.length ?? 0} logs
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// ─── Settings Tab ─────────────────────────────────────────────────────────────
interface DailyJobResult {
  orgId: string;
  draftsGenerated: number;
  emailsSent: number;
  emailsSkipped: number;
  emailsBlocked: number;
  emailsFailed: number;
  errors: string[];
}

function SettingsTab() {
  const { toast } = useToast();
  const { data: raw, isLoading } = useQuery<EmailAgentSettings>({ queryKey: ["/api/email-agent/settings"] });

  const [settings, setSettings] = useState<EmailAgentSettings>({
    enabled: false,
    dailyLimit: 10,
    outreachRadius: 25,
    cooldownDays: 30,
    autoGenerateDrafts: true,
    autoSend: false,
    preferredSports: [],
    targetLevels: ["high_school", "club", "travel"],
    defaultEstimatedValue: 2500,
  });
  const [initialized, setInitialized] = useState(false);
  const [jobResult, setJobResult] = useState<DailyJobResult | null>(null);

  if (raw && !initialized) {
    setSettings({ ...settings, ...raw });
    setInitialized(true);
  }

  const saveMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/email-agent/settings", settings).then(r => r.json()),
    onSuccess: () => {
      toast({ title: "Settings saved" });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/settings"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const runJobMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/email-agent/run-daily-job").then(r => r.json()),
    onSuccess: (data: DailyJobResult) => {
      setJobResult(data);
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/overview"] });
      queryClient.invalidateQueries({ queryKey: ["/api/email-agent/queue"] });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/team-training/drafts"] });
      toast({ title: "Agent run complete", description: `Sent ${data.emailsSent} · Drafts ${data.draftsGenerated} · Skipped ${data.emailsSkipped}` });
    },
    onError: (e: any) => toast({ title: "Agent run failed", description: e.message, variant: "destructive" }),
  });

  const set = (k: keyof EmailAgentSettings, v: any) => setSettings(s => ({ ...s, [k]: v }));

  const toggleSport = (sport: string) => {
    const current = settings.preferredSports || [];
    set("preferredSports", current.includes(sport) ? current.filter(s => s !== sport) : [...current, sport]);
  };

  const toggleLevel = (level: string) => {
    const current = settings.targetLevels || [];
    set("targetLevels", current.includes(level) ? current.filter(l => l !== level) : [...current, level]);
  };

  if (isLoading) return <div className="space-y-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-16 w-full" />)}</div>;

  const levels = [
    { key: "high_school", label: "High School" },
    { key: "club", label: "Club" },
    { key: "travel", label: "Travel" },
    { key: "college", label: "College" },
    { key: "adult", label: "Adult" },
    { key: "middle_school", label: "Middle School" },
  ];

  return (
    <div className="space-y-5 max-w-2xl">
      {/* On/Off toggles */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2"><Bot className="h-4 w-4" />Agent Controls</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <Label className="font-medium">Enable Team Outreach Agent</Label>
              <p className="text-xs text-muted-foreground">Allow the agent to find and manage prospects</p>
            </div>
            <Switch checked={settings.enabled ?? false} onCheckedChange={v => set("enabled", v)} data-testid="switch-agent-enabled" />
          </div>
          <div className="flex items-center justify-between">
            <div>
              <Label className="font-medium">Auto-Generate Drafts</Label>
              <p className="text-xs text-muted-foreground">Automatically create email drafts for queued prospects</p>
            </div>
            <Switch checked={settings.autoGenerateDrafts ?? true} onCheckedChange={v => set("autoGenerateDrafts", v)} data-testid="switch-auto-generate" />
          </div>
          <div className="flex items-center justify-between">
            <div>
              <Label className="font-medium">Auto-Send Daily Queue</Label>
              <p className="text-xs text-muted-foreground text-amber-600 dark:text-amber-400">⚠ Emails will send automatically without manual approval</p>
            </div>
            <Switch checked={settings.autoSend ?? false} onCheckedChange={v => set("autoSend", v)} data-testid="switch-auto-send" />
          </div>
        </CardContent>
      </Card>

      {/* Limits & Timing */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2"><Settings2 className="h-4 w-4" />Limits & Timing</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <Label>Daily Email Limit <span className="text-muted-foreground">(max 10)</span></Label>
              <Input
                type="number"
                min={1}
                max={10}
                value={settings.dailyLimit ?? 10}
                onChange={e => set("dailyLimit", Math.min(10, Math.max(1, parseInt(e.target.value) || 10)))}
                className="mt-1"
                data-testid="input-daily-limit"
              />
            </div>
            <div>
              <Label>Outreach Radius (miles)</Label>
              <Input
                type="number"
                min={5}
                max={200}
                value={settings.outreachRadius ?? 25}
                onChange={e => set("outreachRadius", parseInt(e.target.value) || 25)}
                className="mt-1"
                data-testid="input-outreach-radius"
              />
            </div>
            <div>
              <Label>Cooldown Period (days)</Label>
              <Input
                type="number"
                min={7}
                max={365}
                value={settings.cooldownDays ?? 30}
                onChange={e => set("cooldownDays", parseInt(e.target.value) || 30)}
                className="mt-1"
                data-testid="input-cooldown-days"
              />
            </div>
          </div>
          <div>
            <Label>Default Estimated Team Value ($)</Label>
            <Input
              type="number"
              min={0}
              value={settings.defaultEstimatedValue ?? 2500}
              onChange={e => set("defaultEstimatedValue", parseInt(e.target.value) || 2500)}
              className="mt-1 max-w-xs"
              data-testid="input-default-value"
            />
            <p className="text-xs text-muted-foreground mt-1">Used for pipeline estimate when no specific value is set on a prospect</p>
          </div>
        </CardContent>
      </Card>

      {/* Preferred Sports */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2"><Target className="h-4 w-4" />Preferred Sports</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-xs text-muted-foreground mb-3">Select sports to prioritize during prospect research. Leave empty to target all sports.</p>
          <div className="flex flex-wrap gap-2" data-testid="sports-selector">
            {SPORTS_MULTISELECT.map(sport => {
              const selected = (settings.preferredSports || []).includes(sport);
              return (
                <button
                  key={sport}
                  onClick={() => toggleSport(sport)}
                  className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${selected ? "bg-primary text-primary-foreground border-primary" : "border-muted-foreground/30 text-muted-foreground hover:border-primary hover:text-foreground"}`}
                  data-testid={`sport-toggle-${sport.toLowerCase().replace(/\s/g, "-")}`}
                >
                  {sport}
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Target Levels */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2"><TrendingUp className="h-4 w-4" />Target Levels</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2" data-testid="levels-selector">
            {levels.map(({ key, label }) => {
              const selected = (settings.targetLevels || []).includes(key);
              return (
                <button
                  key={key}
                  onClick={() => toggleLevel(key)}
                  className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${selected ? "bg-primary text-primary-foreground border-primary" : "border-muted-foreground/30 text-muted-foreground hover:border-primary hover:text-foreground"}`}
                  data-testid={`level-toggle-${key}`}
                >
                  {label}
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending} data-testid="button-save-settings">
        {saveMutation.isPending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
        Save Settings
      </Button>

      {/* Manual Run */}
      <Card className="border-primary/30 bg-primary/5">
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <Zap className="h-4 w-4 text-primary" />
            Run Agent Now
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Trigger today's full outreach cycle immediately — builds queue, generates drafts
            {settings.autoSend ? ", and sends emails" : ", and leaves drafts awaiting approval"}.
          </p>
          <Button
            onClick={() => { setJobResult(null); runJobMutation.mutate(); }}
            disabled={runJobMutation.isPending}
            className="gap-2"
            data-testid="button-run-agent-now"
          >
            {runJobMutation.isPending
              ? <><Loader2 className="h-4 w-4 animate-spin" />Running Agent…</>
              : <><Zap className="h-4 w-4" />Run Today's Agent Now</>
            }
          </Button>

          {jobResult && (
            <div className="mt-3 rounded-lg border bg-background p-4 space-y-3" data-testid="agent-run-result">
              <p className="text-sm font-semibold flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-500" />
                Agent Run Complete
              </p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="rounded-md bg-green-500/10 p-3 text-center" data-testid="result-drafts-generated">
                  <p className="text-2xl font-bold text-green-600 dark:text-green-400">{jobResult.draftsGenerated}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Drafts Generated</p>
                </div>
                <div className="rounded-md bg-blue-500/10 p-3 text-center" data-testid="result-emails-sent">
                  <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">{jobResult.emailsSent}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Emails Sent</p>
                </div>
                <div className="rounded-md bg-yellow-500/10 p-3 text-center" data-testid="result-emails-skipped">
                  <p className="text-2xl font-bold text-yellow-600 dark:text-yellow-400">{jobResult.emailsSkipped}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Skipped</p>
                </div>
                <div className="rounded-md bg-red-500/10 p-3 text-center" data-testid="result-emails-blocked">
                  <p className="text-2xl font-bold text-red-600 dark:text-red-400">{jobResult.emailsBlocked + jobResult.emailsFailed}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">Blocked / Failed</p>
                </div>
              </div>
              {jobResult.errors.length > 0 && (
                <div className="rounded-md bg-destructive/10 p-3 space-y-1">
                  <p className="text-xs font-semibold text-destructive flex items-center gap-1">
                    <AlertCircle className="h-3.5 w-3.5" />
                    {jobResult.errors.length} error{jobResult.errors.length > 1 ? "s" : ""}
                  </p>
                  {jobResult.errors.map((e, i) => (
                    <p key={i} className="text-xs text-muted-foreground">{e}</p>
                  ))}
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function CommunicationHistoryPage() {
  const [activeTab, setActiveTab] = useState("overview");

  return (
    <div className="p-4 md:p-6 space-y-5 max-w-7xl mx-auto pb-24 md:pb-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2">
            <Bot className="h-6 w-6 text-primary" />
            <h1 className="text-2xl font-bold tracking-tight" data-testid="heading-email-agent">Email Agent</h1>
          </div>
          <p className="text-muted-foreground text-sm mt-1" data-testid="text-email-agent-subtitle">
            Manage outreach, prospects, sent emails, and AI-generated follow-ups.
          </p>
        </div>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <div className="overflow-x-auto -mx-4 px-4 md:mx-0 md:px-0">
          <TabsList className="flex w-max gap-1 min-w-full md:w-auto" data-testid="tabs-email-agent">
            <TabsTrigger value="overview" className="whitespace-nowrap" data-testid="tab-overview">
              <TrendingUp className="h-3.5 w-3.5 mr-1.5 hidden sm:inline" />
              Overview
            </TabsTrigger>
            <TabsTrigger value="prospects" className="whitespace-nowrap" data-testid="tab-prospects">
              <Users className="h-3.5 w-3.5 mr-1.5 hidden sm:inline" />
              Prospects
            </TabsTrigger>
            <TabsTrigger value="drafts" className="whitespace-nowrap" data-testid="tab-drafts">
              <Bot className="h-3.5 w-3.5 mr-1.5 hidden sm:inline" />
              Drafts
            </TabsTrigger>
            <TabsTrigger value="sent" className="whitespace-nowrap" data-testid="tab-sent">
              <Mail className="h-3.5 w-3.5 mr-1.5 hidden sm:inline" />
              Sent
            </TabsTrigger>
            <TabsTrigger value="settings" className="whitespace-nowrap" data-testid="tab-settings">
              <Settings2 className="h-3.5 w-3.5 mr-1.5 hidden sm:inline" />
              Settings
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="overview" className="mt-4">
          <OverviewTab />
        </TabsContent>
        <TabsContent value="prospects" className="mt-4">
          <ProspectsTab />
        </TabsContent>
        <TabsContent value="drafts" className="mt-4">
          <DraftsTab />
        </TabsContent>
        <TabsContent value="sent" className="mt-4">
          <SentTab />
        </TabsContent>
        <TabsContent value="settings" className="mt-4">
          <SettingsTab />
        </TabsContent>
      </Tabs>

      {/* Mobile sticky bottom button */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-background/95 border-t backdrop-blur-md md:hidden z-40" data-testid="mobile-agent-bar">
        <Button className="w-full" size="sm" onClick={() => setActiveTab("overview")} data-testid="button-ask-email-agent">
          <Bot className="h-4 w-4 mr-2" />
          Ask Email Agent
        </Button>
      </div>
    </div>
  );
}
