/**
 * Agent Billing Engine — Phase 8
 *
 * Tracks all revenue generated by agents and computes developer royalties.
 * Supports: install, usage, subscription, and revenue_recovered streams.
 * Developer share: 30% (configurable per account). Platform share: 70%.
 *
 * Infrastructure only — no payment processing yet.
 */

import { db } from "./db";
import {
  agentRevenueEvents,
  developerAccounts,
  developerRoyaltyAccounts,
  royaltyDistributions,
  agentTemplates,
  orgInstalledAgents,
  agentSubmissions,
  type RoyaltyDistribution,
} from "@shared/schema";
import { eq, and, gte, sql, desc } from "drizzle-orm";
import { AGENT_IDENTITIES } from "./agent-identities";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface BillingStatement {
  developerId: string;
  period: string;               // "2026-05"
  grossRevenue: number;
  platformShare: number;
  developerShare: number;
  royaltyRate: number;
  breakdown: {
    installs: number;
    usage: number;
    subscription: number;
    revenueRecovered: number;
  };
  agentBreakdown: Array<{
    agentId: string;
    agentName: string;
    gross: number;
    royalty: number;
    events: number;
  }>;
}

export interface MarketplaceRevenueSummary {
  totalGrossRevenue: number;
  totalDeveloperRoyalties: number;
  totalPlatformRevenue: number;
  bySource: Record<string, { gross: number; royalties: number }>;
  byAgent: Array<{ agentId: string; agentName: string; gross: number; royalties: number }>;
  period: string;
}

// ─── Ensure Royalty Account ───────────────────────────────────────────────────

async function ensureRoyaltyAccount(developerId: string): Promise<typeof developerRoyaltyAccounts.$inferSelect> {
  const existing = await db.select().from(developerRoyaltyAccounts).where(
    eq(developerRoyaltyAccounts.developerId, developerId)
  ).catch(() => []);
  if (existing[0]) return existing[0];

  const nextPayout = new Date();
  nextPayout.setMonth(nextPayout.getMonth() + 1);
  nextPayout.setDate(1);

  const [created] = await db.insert(developerRoyaltyAccounts).values({
    developerId, balance: 0, lifetimeEarned: 0, lifetimePaid: 0, pendingAmount: 0,
    nextPayoutDate: nextPayout, payoutFrequency: "monthly",
  }).returning();
  return created;
}

// ─── Generate Royalty Distributions ──────────────────────────────────────────

export async function generateRoyaltyDistributions(period?: string): Promise<RoyaltyDistribution[]> {
  const currentPeriod = period ?? new Date().toISOString().substring(0, 7); // "2026-05"

  // Find agents that have developer associations via submissions
  const submissions = await db.select().from(agentSubmissions)
    .where(eq(agentSubmissions.submissionStatus, "published")).catch(() => []);

  // Build agentId → developerId map
  const agentDevMap: Record<string, string> = {};
  for (const sub of submissions) {
    if (sub.agentTemplateId) {
      const templates = await db.select({ agentId: agentTemplates.agentId }).from(agentTemplates)
        .where(eq(agentTemplates.id, sub.agentTemplateId)).catch(() => []);
      if (templates[0]) agentDevMap[templates[0].agentId] = sub.developerId;
    }
  }

  // Get revenue events for the period
  const [yearMonth] = currentPeriod.split("-");
  const events = await db.select().from(agentRevenueEvents)
    .where(eq(agentRevenueEvents.period, currentPeriod)).catch(() => []);

  const distributions: typeof royaltyDistributions.$inferSelect[] = [];

  // Group events by agent
  const byAgent = events.reduce((acc, e) => {
    if (!acc[e.agentId]) acc[e.agentId] = { install: 0, usage: 0, subscription: 0, revenue_recovered: 0, total: 0 };
    const src = (e.eventType ?? "usage") as keyof typeof acc[string];
    if (src in acc[e.agentId]) (acc[e.agentId] as any)[src] += e.amount ?? 0;
    acc[e.agentId].total += e.amount ?? 0;
    return acc;
  }, {} as Record<string, any>);

  for (const [agentId, rev] of Object.entries(byAgent)) {
    const developerId = agentDevMap[agentId];
    if (!developerId) continue;

    const devAccount = await db.select().from(developerAccounts).where(
      eq(developerAccounts.id, developerId)
    ).catch(() => []);
    const royaltyRate = devAccount[0]?.revenueShareRate ?? 0.30;

    for (const [source, amount] of Object.entries(rev)) {
      if (source === "total" || (amount as number) === 0) continue;
      const gross = amount as number;
      const developerShare = gross * royaltyRate;
      const platformShare = gross * (1 - royaltyRate);

      await ensureRoyaltyAccount(developerId);

      const existing = await db.select().from(royaltyDistributions).where(
        and(
          eq(royaltyDistributions.developerId, developerId),
          eq(royaltyDistributions.agentId, agentId),
          eq(royaltyDistributions.revenueSource, source),
          eq(royaltyDistributions.period, currentPeriod)
        )
      ).catch(() => []);

      if (existing.length === 0) {
        const [dist] = await db.insert(royaltyDistributions).values({
          developerId, agentId, revenueSource: source, grossRevenue: gross,
          platformShare, developerShare, platformShareRate: 1 - royaltyRate,
          developerShareRate: royaltyRate, payoutStatus: "pending", period: currentPeriod,
        }).returning();
        distributions.push(dist);
      }
    }
  }

  return distributions;
}

// ─── Monthly Billing Statement ────────────────────────────────────────────────

export async function generateMonthlyStatement(developerId: string, period?: string): Promise<BillingStatement> {
  const currentPeriod = period ?? new Date().toISOString().substring(0, 7);

  const [devAccount, distributions] = await Promise.all([
    db.select().from(developerAccounts).where(eq(developerAccounts.id, developerId)).catch(() => []),
    db.select().from(royaltyDistributions).where(
      and(eq(royaltyDistributions.developerId, developerId), eq(royaltyDistributions.period, currentPeriod))
    ).catch(() => []),
  ]);

  const royaltyRate = devAccount[0]?.revenueShareRate ?? 0.30;
  let gross = 0, devShare = 0;
  const breakdown = { installs: 0, usage: 0, subscription: 0, revenueRecovered: 0 };
  const agentMap: Record<string, { gross: number; royalty: number; events: number }> = {};

  for (const d of distributions) {
    gross += d.grossRevenue ?? 0;
    devShare += d.developerShare ?? 0;
    const src = d.revenueSource ?? "usage";
    if (src === "install") breakdown.installs += d.grossRevenue ?? 0;
    else if (src === "usage") breakdown.usage += d.grossRevenue ?? 0;
    else if (src === "subscription") breakdown.subscription += d.grossRevenue ?? 0;
    else if (src === "revenue_recovered") breakdown.revenueRecovered += d.grossRevenue ?? 0;

    if (!agentMap[d.agentId]) agentMap[d.agentId] = { gross: 0, royalty: 0, events: 0 };
    agentMap[d.agentId].gross += d.grossRevenue ?? 0;
    agentMap[d.agentId].royalty += d.developerShare ?? 0;
    agentMap[d.agentId].events++;
  }

  const agentBreakdown = Object.entries(agentMap).map(([agentId, data]) => ({
    agentId,
    agentName: AGENT_IDENTITIES[agentId]?.agentName ?? agentId,
    ...data,
  }));

  return {
    developerId,
    period: currentPeriod,
    grossRevenue: Math.round(gross * 100) / 100,
    platformShare: Math.round((gross - devShare) * 100) / 100,
    developerShare: Math.round(devShare * 100) / 100,
    royaltyRate,
    breakdown,
    agentBreakdown,
  };
}

// ─── Marketplace Revenue Summary ──────────────────────────────────────────────

export async function computeMarketplaceRevenue(period?: string): Promise<MarketplaceRevenueSummary> {
  const currentPeriod = period ?? new Date().toISOString().substring(0, 7);

  const allEvents = await db.select().from(agentRevenueEvents).catch(() => []);
  const periodEvents = period ? allEvents.filter(e => e.period === period) : allEvents;

  let totalGross = 0, totalDevRoyalties = 0;
  const bySource: Record<string, { gross: number; royalties: number }> = {};
  const byAgentMap: Record<string, { gross: number; royalties: number }> = {};

  for (const e of periodEvents) {
    const gross = e.amount ?? 0;
    const royalty = e.royaltyAmount ?? gross * 0.30;
    totalGross += gross;
    totalDevRoyalties += royalty;

    const src = e.eventType ?? "usage";
    if (!bySource[src]) bySource[src] = { gross: 0, royalties: 0 };
    bySource[src].gross += gross;
    bySource[src].royalties += royalty;

    if (!byAgentMap[e.agentId]) byAgentMap[e.agentId] = { gross: 0, royalties: 0 };
    byAgentMap[e.agentId].gross += gross;
    byAgentMap[e.agentId].royalties += royalty;
  }

  const byAgent = Object.entries(byAgentMap)
    .map(([agentId, data]) => ({
      agentId,
      agentName: AGENT_IDENTITIES[agentId]?.agentName ?? agentId,
      ...data,
    }))
    .sort((a, b) => b.gross - a.gross);

  return {
    totalGrossRevenue: Math.round(totalGross * 100) / 100,
    totalDeveloperRoyalties: Math.round(totalDevRoyalties * 100) / 100,
    totalPlatformRevenue: Math.round((totalGross - totalDevRoyalties) * 100) / 100,
    bySource,
    byAgent,
    period: currentPeriod,
  };
}

// ─── Developer Royalty Balance ─────────────────────────────────────────────────

export async function getDeveloperRoyaltyBalance(developerId: string) {
  const [account, pending] = await Promise.all([
    ensureRoyaltyAccount(developerId),
    db.select().from(royaltyDistributions).where(
      and(eq(royaltyDistributions.developerId, developerId), eq(royaltyDistributions.payoutStatus, "pending"))
    ).catch(() => []),
  ]);

  const pendingTotal = pending.reduce((s, d) => s + (d.developerShare ?? 0), 0);
  await db.update(developerRoyaltyAccounts).set({ pendingAmount: pendingTotal, updatedAt: new Date() })
    .where(eq(developerRoyaltyAccounts.developerId, developerId)).catch(() => {});

  return {
    ...account,
    pendingAmount: pendingTotal,
  };
}
