import { storage } from "../storage";
import { generateOutreachEmail, generateOutreachEmailFromVariant } from "../team-training-prospecting";
import { type OrgBranding } from "../email";
import { guardedSendTeamTrainingOutreachEmail } from "../services/guarded-outbound-email";
import { logTriggerEvent, updateTriggerEvent, detectTriggerCollision, buildTriggerContextForProspect } from "./trigger-logger";

let initialized = false;

export interface DailyJobResult {
  orgId: string;
  draftsGenerated: number;
  emailsSent: number;
  emailsSkipped: number;
  emailsBlocked: number;
  emailsFailed: number;
  errors: string[];
}

async function getOrgBrandingLocal(orgId: string): Promise<OrgBranding | undefined> {
  try {
    const org = await storage.getOrganizationById(orgId);
    if (!org) return undefined;
    const owner = org.ownerUserId ? await storage.getUser(org.ownerUserId) : null;
    return {
      name: org.name,
      accentColor: org.primaryColor || undefined,
      emailPrimaryColor: org.emailPrimaryColor || undefined,
      emailSecondaryColor: org.emailSecondaryColor || undefined,
      ownerName: owner ? `${owner.firstName} ${owner.lastName}`.trim() : undefined,
      ownerEmail: org.ownerEmail || undefined,
    };
  } catch {
    return undefined;
  }
}

async function getCoachNameForOrg(orgId: string): Promise<string> {
  try {
    const org = await storage.getOrganizationById(orgId);
    if (!org) return "Coach";
    const ownerCoach = org.ownerEmail ? await storage.getCoachProfileByEmail(org.ownerEmail) : null;
    const coachUser = ownerCoach ? await storage.getUser(ownerCoach.userId) : null;
    if (coachUser?.firstName) return `${coachUser.firstName} ${coachUser.lastName || ""}`.trim();
    const owner = org.ownerUserId ? await storage.getUser(org.ownerUserId) : null;
    if (owner?.firstName) return `${owner.firstName} ${owner.lastName || ""}`.trim();
    return "Coach";
  } catch {
    return "Coach";
  }
}

export async function runEmailAgentForOrg(orgId: string, triggerSource: "cron_8_30am" | "user_click" | "api_call" = "cron_8_30am"): Promise<DailyJobResult> {
  const result: DailyJobResult = {
    orgId,
    draftsGenerated: 0,
    emailsSent: 0,
    emailsSkipped: 0,
    emailsBlocked: 0,
    emailsFailed: 0,
    errors: [],
  };

  try {
    const settings = await storage.getEmailAgentSettings(orgId);

    if (!settings.enabled) {
      console.log(`[Email Agent Cron] org ${orgId} — agent not enabled, skipping`);
      return result;
    }

    const dailyLimit = Math.min(typeof settings.dailyLimit === "number" ? settings.dailyLimit : 10, 10);
    const autoSend: boolean = settings.autoSend === true;
    const autoGenerateDrafts: boolean = settings.autoGenerateDrafts !== false;

    console.log(`[Email Agent Cron] org ${orgId} — running (autoSend=${autoSend}, limit=${dailyLimit})`);

    const queue = await storage.buildDailyOutreachQueue(orgId, dailyLimit);
    console.log(`[Email Agent Cron] draft queue built for org ${orgId}: ${queue.length} prospects queued`);

    if (queue.length === 0) {
      console.log(`[Email Agent Cron] org ${orgId} — no eligible prospects in queue`);
      return result;
    }

    const org = await storage.getOrganizationById(orgId);
    const businessName = org?.name || "Our Training Facility";
    const coachName = await getCoachNameForOrg(orgId);
    const branding = await getOrgBrandingLocal(orgId);

    for (const prospect of queue) {
      // ── Phase 9: Build trigger history context for this prospect ──────────
      const triggerHistoryCtx = await buildTriggerContextForProspect(orgId, prospect.id);

      // ── Log BEFORE execution decision ──────────────────────────────────────
      const triggerEventId = await logTriggerEvent({
        organizationId: orgId,
        prospectId: prospect.id,
        prospectName: prospect.prospectName,
        triggerType: "daily_outreach",
        triggerSource,
        actionType: "send_initial_email",
        reasoning: `Daily outreach queue evaluation for ${prospect.prospectName}${triggerHistoryCtx ? " " + triggerHistoryCtx : ""}`,
      });

      if (!prospect.contactEmail) {
        result.emailsSkipped++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Skipped: no email address`,
        });
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "MISSING_EMAIL",
          reasoning: "Prospect has no contact email address",
        });
        continue;
      }

      if (prospect.outreachStatus === "Do Not Contact") {
        result.emailsBlocked++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Blocked: Do Not Contact`,
        });
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "DNC",
          reasoning: "Prospect is marked Do Not Contact",
        });
        continue;
      }

      const optedOut = await storage.isProspectOptedOut(orgId, prospect.contactEmail);
      if (optedOut) {
        result.emailsBlocked++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Blocked: opted out`,
        });
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "OPTED_OUT",
          reasoning: "Prospect email is on the opt-out list",
        });
        continue;
      }

      // ── Collision detection ─────────────────────────────────────────────────
      const collision = await detectTriggerCollision(orgId, prospect.id, 5);
      if (collision) {
        await storage.updateEmailTriggerEvent(triggerEventId, {
          collisionDetected: true,
          collisionDetails: collision,
        });
        console.warn(`[Email Agent Cron] Collision detected for ${prospect.prospectName}: ${collision}`);
      }

      const existingDrafts = await storage.getOutreachDraftsByProspect(prospect.id);
      const approvedUnsent = existingDrafts.find(d => d.approved && !d.sentAt);
      const anyUnsent = existingDrafts.find(d => !d.sentAt);

      let draftToSend = approvedUnsent ?? null;

      if (!anyUnsent && autoGenerateDrafts) {
        try {
          // Phase 9: build stage + quality context for injection
          let conversationStage: string | undefined;
          let contactQualityScore: number | undefined;
          let stageContext: string | undefined;
          try {
            const { computeContactQualityScore } = await import("./contact-quality");
            const { computeConversationStage, getStageMessageingGuidance } = await import("./conversation-stage");
            const qResult = computeContactQualityScore(prospect);
            contactQualityScore = qResult.score;
            const sentForProspect = existingDrafts.filter((d) => !!d.sentAt);
            const latest = sentForProspect[sentForProspect.length - 1] ?? null;
            const stage = computeConversationStage({
              prospect,
              totalSent: sentForProspect.length,
              openCount: sentForProspect.filter((d) => !!d.openedAt).length,
              clicked: sentForProspect.some((d) => !!d.clickedAt),
              replied: sentForProspect.some((d) => !!d.repliedAt),
              replyClassification: (latest?.replyClassification ?? null) as any,
              deal: null,
            });
            conversationStage = stage;
            stageContext = getStageMessageingGuidance(stage);
          } catch {
            // context injection is best-effort
          }

          const emailParams = {
            businessName,
            coachName,
            prospectName: prospect.prospectName,
            sport: prospect.sport || "your sport",
            city: prospect.city || "your area",
            contactName: prospect.contactName || "unknown",
            conversationStage,
            contactQualityScore,
            stageContext,
          };

          // Try to use a variant, fall back to free-form generation
          const variant = await storage.selectVariantForEmail(orgId);
          let generated: { subject: string; body: string };
          let variantId: string | undefined;

          if (variant) {
            generated = await generateOutreachEmailFromVariant(emailParams, variant);
            variantId = variant.id;
            // Increment timesUsed
            await storage.updateEmailMessageVariant(variant.id, { timesUsed: (variant.timesUsed ?? 0) + 1 });
          } else {
            generated = await generateOutreachEmail(emailParams);
          }

          const saved = await storage.createOutreachDraft({
            orgId,
            prospectId: prospect.id,
            subject: generated.subject,
            body: generated.body,
            approved: autoSend,
            approvedAt: autoSend ? new Date() : undefined,
            messageVariantId: variantId,
          });

          await storage.logOutreachEvent({
            orgId,
            prospectId: prospect.id,
            draftId: saved.id,
            eventType: "draft_created",
            description: `[Auto] Draft generated by Email Agent`,
          });

          await updateTriggerEvent(triggerEventId, {
            wasExecuted: false,
            executionBlocked: false,
            outreachDraftId: saved.id,
            reasoning: `Draft generated for ${prospect.prospectName}${autoSend ? " (auto-send enabled)" : " (awaiting approval)"}`,
          });

          result.draftsGenerated++;
          console.log(`[Email Agent Cron] draft generated for ${prospect.prospectName}`);

          if (autoSend) {
            draftToSend = saved;
          }
        } catch (genErr: any) {
          console.error(`[Email Agent Cron] error — draft gen failed for ${prospect.prospectName}:`, genErr.message);
          result.errors.push(`Draft gen failed (${prospect.prospectName}): ${genErr.message}`);
          result.emailsFailed++;
          await updateTriggerEvent(triggerEventId, {
            wasExecuted: false,
            executionBlocked: true,
            blockReason: "INVALID_STAGE",
            reasoning: `Draft generation failed: ${genErr.message}`,
          });
          continue;
        }
      } else if (anyUnsent && !approvedUnsent && autoSend) {
        const updated = await storage.updateOutreachDraft(anyUnsent.id, {
          approved: true,
          approvedAt: new Date(),
        });
        draftToSend = updated ?? anyUnsent;
      } else if (!autoSend) {
        result.emailsSkipped++;
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: false,
          reasoning: "Auto-send disabled — draft queued for manual approval",
        });
        continue;
      }

      if (!autoSend || !draftToSend) {
        result.emailsSkipped++;
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: false,
          reasoning: "No draft available to send",
        });
        continue;
      }

      if (!draftToSend.body || draftToSend.body.trim().length === 0) {
        result.emailsSkipped++;
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "INVALID_STAGE",
          reasoning: "Draft body is empty",
        });
        continue;
      }

      const currentOverview = await storage.getEmailAgentOverview(orgId);
      if (currentOverview.sentToday >= dailyLimit) {
        console.log(`[Email Agent Cron] daily cap reached for org ${orgId} (${currentOverview.sentToday}/${dailyLimit})`);
        result.emailsSkipped++;
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "DAILY_LIMIT_REACHED",
          reasoning: `Daily send cap reached: ${currentOverview.sentToday}/${dailyLimit}`,
        });
        break;
      }

      try {
        // ── PHASE 5: Autonomy Policy Gate — every auto-send goes through the policy engine ──
        const { evaluatePolicy } = await import("../services/autonomy-policy-engine");
        const policy = await evaluatePolicy({
          orgId,
          actionType: "send_initial_email",
          recipientEmail: prospect.contactEmail,
          confidence: 0.80,
          riskLevel: "low",
          bodyText: draftToSend.body ?? undefined,
          isFirstContact: true,
          isNewRecipient: true,
        }).catch((e) => {
          // PHASE 3 pattern: fail closed — policy errors → approval_required
          console.warn(`[Email Agent Cron] Policy evaluation failed — defaulting to approval_required (org ${orgId}):`, e?.message);
          return {
            decision: "approval_required" as const,
            reasons: ["Policy evaluation error — defaulting to approval_required"] as string[],
            confidence: 0.80,
            riskLevel: "low" as const,
            policyVersion: "1.0.0",
            evaluatedAt: new Date(),
          };
        });

        if (policy.decision === "blocked") {
          await storage.updateOutreachDraft(draftToSend.id, { approved: false });
          result.emailsBlocked++;
          await updateTriggerEvent(triggerEventId, {
            wasExecuted: false,
            executionBlocked: true,
            blockReason: "POLICY_BLOCKED",
            reasoning: `Autonomy policy blocked: ${policy.reasons.join("; ")}`,
          });
          console.log(`[Email Agent Cron] Policy BLOCKED send to ${prospect.contactEmail}`);
          continue;
        }

        if (policy.decision === "approval_required") {
          try {
            const { db: _db } = await import("../db");
            const { gmailAgentActions } = await import("@shared/schema");
            await _db.insert(gmailAgentActions).values({
              orgId,
              actionType: "initial_outreach_email",
              recipientEmail: prospect.contactEmail,
              subject: draftToSend.subject ?? `Outreach for ${prospect.prospectName}`,
              bodyPreview: (draftToSend.body ?? "").slice(0, 300),
              riskLevel: "low",
              approvalRequired: true,
              status: "proposed",
              communicationDomain: "team_training",
              createdByAgent: "scheduled_email_agent",
              result: { draftId: draftToSend.id, prospectId: prospect.id },
            });
          } catch { /* approval queuing is best-effort */ }
          await storage.updateOutreachDraft(draftToSend.id, { approved: false });
          result.emailsSkipped++;
          await updateTriggerEvent(triggerEventId, {
            wasExecuted: false,
            executionBlocked: false,
            reasoning: `Policy requires approval — queued in AI Comms Center. Reasons: ${policy.reasons.join("; ")}`,
          });
          console.log(`[Email Agent Cron] Policy APPROVAL_REQUIRED for send to ${prospect.contactEmail} — queued`);
          continue;
        }

        // ── PHASE 4: Guarded send through the full Send Guard chain ─────────
        const sendResult = await guardedSendTeamTrainingOutreachEmail({
          orgId,
          recipientEmail: prospect.contactEmail,
          recipientName: prospect.contactName || undefined,
          subject: draftToSend.subject,
          body: draftToSend.body,
          branding,
          trackingId: draftToSend.id,
          sourceSystem: "scheduled_email_agent",
          sourceRecordId: draftToSend.id,
          triggeredBy: "cron",
          emailType: "initial_outreach",
          policyDecision: "auto_execute",
        });

        if (sendResult.blocked) {
          result.emailsBlocked++;
          await updateTriggerEvent(triggerEventId, {
            wasExecuted: false,
            executionBlocked: true,
            blockReason: "POLICY_BLOCKED",
            reasoning: `Send Guard blocked: ${sendResult.blockReason}`,
          });
          console.warn(`[Email Agent Cron] Send Guard blocked send to ${prospect.contactEmail}: ${sendResult.blockReason}`);
          continue;
        }

        const sentAt = new Date();
        await storage.updateOutreachDraft(draftToSend.id, { sentAt });
        await storage.updateTeamTrainingProspect(prospect.id, {
          outreachStatus: "Contacted",
          lastContactedAt: sentAt,
        });
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          draftId: draftToSend.id,
          eventType: "sent",
          description: `[Auto] Outreach sent to ${prospect.contactEmail}`,
        });

        await updateTriggerEvent(triggerEventId, {
          wasExecuted: true,
          executionBlocked: false,
          outreachDraftId: draftToSend.id,
          reasoning: `Initial outreach sent to ${prospect.contactEmail} via ${triggerSource}`,
        });

        // Schedule follow-up sequence
        try {
          const { scheduleFollowUpsForDraft } = await import("./follow-up-cron");
          await scheduleFollowUpsForDraft(orgId, draftToSend.id, prospect.id, sentAt);
        } catch (fuErr: any) {
          console.warn(`[Email Agent Cron] follow-up scheduling error:`, fuErr.message);
        }

        result.emailsSent++;
        console.log(`[Email Agent Cron] sent email to ${prospect.contactEmail} (${prospect.prospectName})`);
      } catch (sendErr: any) {
        console.error(`[Email Agent Cron] error — send failed for ${prospect.contactEmail}:`, sendErr.message);
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          draftId: draftToSend.id,
          eventType: "failed",
          description: `[Auto] Send failed: ${sendErr.message}`,
        });
        await updateTriggerEvent(triggerEventId, {
          wasExecuted: false,
          executionBlocked: true,
          blockReason: "INVALID_STAGE",
          reasoning: `Send failed: ${sendErr.message}`,
        });
        result.emailsFailed++;
        result.errors.push(`Send failed (${prospect.prospectName}): ${sendErr.message}`);
      }
    }

    console.log(
      `[Email Agent Cron] org ${orgId} processed — drafts: ${result.draftsGenerated}, sent: ${result.emailsSent}, skipped: ${result.emailsSkipped}, blocked: ${result.emailsBlocked}, failed: ${result.emailsFailed}`,
    );

    await storage.saveEmailAgentSettings(orgId, {
      ...settings,
      _lastRunAt: new Date().toISOString(),
      _lastRunDate: new Date().toDateString(),
    });

    // Auto-optimize variants every 50 emails sent
    try {
      const perfStats = await storage.getEmailPerformanceStats(orgId);
      if (perfStats.sent > 0 && perfStats.sent % 50 < result.emailsSent) {
        await storage.runVariantOptimization(orgId);
        console.log(`[Email Agent Cron] org ${orgId} — variant optimization triggered at ${perfStats.sent} emails sent`);
      }
    } catch (optErr: any) {
      console.warn(`[Email Agent Cron] variant optimization error:`, optErr.message);
    }
  } catch (err: any) {
    console.error(`[Email Agent Cron] error for org ${orgId}:`, err.message);
    result.errors.push(err.message);
  }

  return result;
}

let dailyJobRunning = false;

async function runDailyJobForAllOrgs(): Promise<void> {
  // Global guard (Priority 3): prevent overlapping runs if 8:30 window spans multiple ticks
  if (dailyJobRunning) {
    console.log(`[Email Agent Cron] daily job still running — skipping duplicate tick`);
    return;
  }
  dailyJobRunning = true;
  console.log(`[Email Agent Cron] running daily job for all orgs`);
  try {
    const orgs = await storage.getAllOrganizations();
    const today = new Date().toDateString();

    for (const org of orgs) {
      try {
        const settings = await storage.getEmailAgentSettings(org.id);
        if (!settings.enabled) continue;
        if (settings._lastRunDate === today) {
          console.log(`[Email Agent Cron] org ${org.id} already ran today, skipping`);
          continue;
        }
        await runEmailAgentForOrg(org.id, "cron_8_30am");
      } catch (err: any) {
        console.error(`[Email Agent Cron] error for org ${org.id}:`, err.message);
      }
    }
  } catch (err: any) {
    console.error(`[Email Agent Cron] error in daily job runner:`, err.message);
  } finally {
    dailyJobRunning = false;
  }
}

function isTimeToRun(): boolean {
  const now = new Date();
  const h = now.getHours();
  const m = now.getMinutes();
  return h === 8 && m >= 30 && m <= 34;
}

export function initializeScheduledEmailAgent(): void {
  if (initialized) {
    console.log("[Email Agent Cron] already initialized, skipping duplicate start");
    return;
  }
  initialized = true;
  console.log("[Email Agent Cron] started — will run daily at 8:30 AM");

  setInterval(async () => {
    if (isTimeToRun()) {
      await runDailyJobForAllOrgs();
    }
  }, 60 * 1000);
}
