import { storage } from "../storage";
import { generateOutreachEmail, generateOutreachEmailFromVariant } from "../team-training-prospecting";
import { sendTeamTrainingOutreachEmail, type OrgBranding } from "../email";

let initialized = false;

export interface DailyJobResult {
  orgId: string;
  draftsGenerated: number;
  emailsSent: number;
  emailsSkipped: number;
  emailsBlocked: number;
  emailsFailed: number;
  errors: string[];
}

async function getOrgBrandingLocal(orgId: string): Promise<OrgBranding | undefined> {
  try {
    const org = await storage.getOrganizationById(orgId);
    if (!org) return undefined;
    const owner = org.ownerUserId ? await storage.getUser(org.ownerUserId) : null;
    return {
      name: org.name,
      accentColor: org.primaryColor || undefined,
      emailPrimaryColor: org.emailPrimaryColor || undefined,
      emailSecondaryColor: org.emailSecondaryColor || undefined,
      ownerName: owner ? `${owner.firstName} ${owner.lastName}`.trim() : undefined,
      ownerEmail: org.ownerEmail || undefined,
    };
  } catch {
    return undefined;
  }
}

async function getCoachNameForOrg(orgId: string): Promise<string> {
  try {
    const org = await storage.getOrganizationById(orgId);
    if (!org) return "Coach";
    const ownerCoach = org.ownerEmail ? await storage.getCoachProfileByEmail(org.ownerEmail) : null;
    const coachUser = ownerCoach ? await storage.getUser(ownerCoach.userId) : null;
    if (coachUser?.firstName) return `${coachUser.firstName} ${coachUser.lastName || ""}`.trim();
    const owner = org.ownerUserId ? await storage.getUser(org.ownerUserId) : null;
    if (owner?.firstName) return `${owner.firstName} ${owner.lastName || ""}`.trim();
    return "Coach";
  } catch {
    return "Coach";
  }
}

export async function runEmailAgentForOrg(orgId: string): Promise<DailyJobResult> {
  const result: DailyJobResult = {
    orgId,
    draftsGenerated: 0,
    emailsSent: 0,
    emailsSkipped: 0,
    emailsBlocked: 0,
    emailsFailed: 0,
    errors: [],
  };

  try {
    const settings = await storage.getEmailAgentSettings(orgId);

    if (!settings.enabled) {
      console.log(`[Email Agent Cron] org ${orgId} — agent not enabled, skipping`);
      return result;
    }

    const dailyLimit = Math.min(typeof settings.dailyLimit === "number" ? settings.dailyLimit : 10, 10);
    const autoSend: boolean = settings.autoSend === true;
    const autoGenerateDrafts: boolean = settings.autoGenerateDrafts !== false;

    console.log(`[Email Agent Cron] org ${orgId} — running (autoSend=${autoSend}, limit=${dailyLimit})`);

    const queue = await storage.buildDailyOutreachQueue(orgId, dailyLimit);
    console.log(`[Email Agent Cron] draft queue built for org ${orgId}: ${queue.length} prospects queued`);

    if (queue.length === 0) {
      console.log(`[Email Agent Cron] org ${orgId} — no eligible prospects in queue`);
      return result;
    }

    const org = await storage.getOrganizationById(orgId);
    const businessName = org?.name || "Our Training Facility";
    const coachName = await getCoachNameForOrg(orgId);
    const branding = await getOrgBrandingLocal(orgId);

    for (const prospect of queue) {
      if (!prospect.contactEmail) {
        result.emailsSkipped++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Skipped: no email address`,
        });
        continue;
      }

      if (prospect.outreachStatus === "Do Not Contact") {
        result.emailsBlocked++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Blocked: Do Not Contact`,
        });
        continue;
      }

      const optedOut = await storage.isProspectOptedOut(orgId, prospect.contactEmail);
      if (optedOut) {
        result.emailsBlocked++;
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          eventType: "skipped",
          description: `[Auto] Blocked: opted out`,
        });
        continue;
      }

      const existingDrafts = await storage.getOutreachDraftsByProspect(prospect.id);
      const approvedUnsent = existingDrafts.find(d => d.approved && !d.sentAt);
      const anyUnsent = existingDrafts.find(d => !d.sentAt);

      let draftToSend = approvedUnsent ?? null;

      if (!anyUnsent && autoGenerateDrafts) {
        try {
          const emailParams = {
            businessName,
            coachName,
            prospectName: prospect.prospectName,
            sport: prospect.sport || "your sport",
            city: prospect.city || "your area",
            contactName: prospect.contactName || "unknown",
          };

          // Try to use a variant, fall back to free-form generation
          const variant = await storage.selectVariantForEmail(orgId);
          let generated: { subject: string; body: string };
          let variantId: string | undefined;

          if (variant) {
            generated = await generateOutreachEmailFromVariant(emailParams, variant);
            variantId = variant.id;
            // Increment timesUsed
            await storage.updateEmailMessageVariant(variant.id, { timesUsed: (variant.timesUsed ?? 0) + 1 });
          } else {
            generated = await generateOutreachEmail(emailParams);
          }

          const saved = await storage.createOutreachDraft({
            orgId,
            prospectId: prospect.id,
            subject: generated.subject,
            body: generated.body,
            approved: autoSend,
            approvedAt: autoSend ? new Date() : undefined,
            messageVariantId: variantId,
          });

          await storage.logOutreachEvent({
            orgId,
            prospectId: prospect.id,
            draftId: saved.id,
            eventType: "draft_created",
            description: `[Auto] Draft generated by Email Agent`,
          });

          result.draftsGenerated++;
          console.log(`[Email Agent Cron] draft generated for ${prospect.prospectName}`);

          if (autoSend) {
            draftToSend = saved;
          }
        } catch (genErr: any) {
          console.error(`[Email Agent Cron] error — draft gen failed for ${prospect.prospectName}:`, genErr.message);
          result.errors.push(`Draft gen failed (${prospect.prospectName}): ${genErr.message}`);
          result.emailsFailed++;
          continue;
        }
      } else if (anyUnsent && !approvedUnsent && autoSend) {
        const updated = await storage.updateOutreachDraft(anyUnsent.id, {
          approved: true,
          approvedAt: new Date(),
        });
        draftToSend = updated ?? anyUnsent;
      } else if (!autoSend) {
        result.emailsSkipped++;
        continue;
      }

      if (!autoSend || !draftToSend) {
        result.emailsSkipped++;
        continue;
      }

      if (!draftToSend.body || draftToSend.body.trim().length === 0) {
        result.emailsSkipped++;
        continue;
      }

      const currentOverview = await storage.getEmailAgentOverview(orgId);
      if (currentOverview.sentToday >= dailyLimit) {
        console.log(`[Email Agent Cron] daily cap reached for org ${orgId} (${currentOverview.sentToday}/${dailyLimit})`);
        result.emailsSkipped++;
        break;
      }

      try {
        await sendTeamTrainingOutreachEmail(
          prospect.contactEmail,
          draftToSend.subject,
          draftToSend.body,
          branding,
          draftToSend.id,
        );

        const sentAt = new Date();
        await storage.updateOutreachDraft(draftToSend.id, { sentAt });
        await storage.updateTeamTrainingProspect(prospect.id, {
          outreachStatus: "Contacted",
          lastContactedAt: sentAt,
        });
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          draftId: draftToSend.id,
          eventType: "sent",
          description: `[Auto] Outreach sent to ${prospect.contactEmail}`,
        });

        // Schedule follow-up sequence
        try {
          const { scheduleFollowUpsForDraft } = await import("./follow-up-cron");
          await scheduleFollowUpsForDraft(orgId, draftToSend.id, prospect.id, sentAt);
        } catch (fuErr: any) {
          console.warn(`[Email Agent Cron] follow-up scheduling error:`, fuErr.message);
        }

        result.emailsSent++;
        console.log(`[Email Agent Cron] sent email to ${prospect.contactEmail} (${prospect.prospectName})`);
      } catch (sendErr: any) {
        console.error(`[Email Agent Cron] error — send failed for ${prospect.contactEmail}:`, sendErr.message);
        await storage.logOutreachEvent({
          orgId,
          prospectId: prospect.id,
          draftId: draftToSend.id,
          eventType: "failed",
          description: `[Auto] Send failed: ${sendErr.message}`,
        });
        result.emailsFailed++;
        result.errors.push(`Send failed (${prospect.prospectName}): ${sendErr.message}`);
      }
    }

    console.log(
      `[Email Agent Cron] org ${orgId} processed — drafts: ${result.draftsGenerated}, sent: ${result.emailsSent}, skipped: ${result.emailsSkipped}, blocked: ${result.emailsBlocked}, failed: ${result.emailsFailed}`,
    );

    await storage.saveEmailAgentSettings(orgId, {
      ...settings,
      _lastRunAt: new Date().toISOString(),
      _lastRunDate: new Date().toDateString(),
    });

    // Auto-optimize variants every 50 emails sent
    try {
      const perfStats = await storage.getEmailPerformanceStats(orgId);
      if (perfStats.sent > 0 && perfStats.sent % 50 < result.emailsSent) {
        await storage.runVariantOptimization(orgId);
        console.log(`[Email Agent Cron] org ${orgId} — variant optimization triggered at ${perfStats.sent} emails sent`);
      }
    } catch (optErr: any) {
      console.warn(`[Email Agent Cron] variant optimization error:`, optErr.message);
    }
  } catch (err: any) {
    console.error(`[Email Agent Cron] error for org ${orgId}:`, err.message);
    result.errors.push(err.message);
  }

  return result;
}

async function runDailyJobForAllOrgs(): Promise<void> {
  console.log(`[Email Agent Cron] running daily job for all orgs`);
  try {
    const orgs = await storage.getAllOrganizations();
    const today = new Date().toDateString();

    for (const org of orgs) {
      try {
        const settings = await storage.getEmailAgentSettings(org.id);
        if (!settings.enabled) continue;
        if (settings._lastRunDate === today) {
          console.log(`[Email Agent Cron] org ${org.id} already ran today, skipping`);
          continue;
        }
        await runEmailAgentForOrg(org.id);
      } catch (err: any) {
        console.error(`[Email Agent Cron] error for org ${org.id}:`, err.message);
      }
    }
  } catch (err: any) {
    console.error(`[Email Agent Cron] error in daily job runner:`, err.message);
  }
}

function isTimeToRun(): boolean {
  const now = new Date();
  const h = now.getHours();
  const m = now.getMinutes();
  return h === 8 && m >= 30 && m <= 34;
}

export function initializeScheduledEmailAgent(): void {
  if (initialized) {
    console.log("[Email Agent Cron] already initialized, skipping duplicate start");
    return;
  }
  initialized = true;
  console.log("[Email Agent Cron] started — will run daily at 8:30 AM");

  setInterval(async () => {
    if (isTimeToRun()) {
      await runDailyJobForAllOrgs();
    }
  }, 60 * 1000);
}
