/**
 * Route guard audit.
 *
 *   npm run audit:routes              report routes with no middleware
 *   npm run audit:routes -- --update  rewrite config/public-routes.json
 *
 * The allowlist is deliberately a review queue, not a rug. Every entry
 * generated by --update starts as UNREVIEWED; replacing that with a real
 * reason is how the backlog gets worked down.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  findRouteRegistrations,
  auditRoutes,
  routeKey,
  type RouteRegistration,
  type PublicRouteEntry,
} from "../server/lib/route-guard-audit";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SERVER_DIR = path.join(repoRoot, "server");
const ALLOWLIST_PATH = path.join(repoRoot, "config", "public-routes.json");

const SKIP_DIRECTORIES = new Set(["__tests__", "tests", "node_modules"]);

export function collectSourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (!SKIP_DIRECTORIES.has(entry)) collectSourceFiles(full, acc);
      continue;
    }
    if (!entry.endsWith(".ts")) continue;
    if (entry.endsWith(".test.ts") || entry.endsWith(".spec.ts")) continue;
    acc.push(full);
  }
  return acc;
}

export function collectRegistrations(): RouteRegistration[] {
  const registrations: RouteRegistration[] = [];
  for (const file of collectSourceFiles(SERVER_DIR)) {
    const relative = path.relative(repoRoot, file);
    for (const route of findRouteRegistrations(readFileSync(file, "utf8"), relative)) {
      if (route.path.startsWith("/api/")) registrations.push(route);
    }
  }
  return registrations;
}

export function readAllowlist(): PublicRouteEntry[] {
  try {
    return JSON.parse(readFileSync(ALLOWLIST_PATH, "utf8")).routes ?? [];
  } catch {
    return [];
  }
}

function main() {
  const update = process.argv.includes("--update");
  const registrations = collectRegistrations();
  const unguarded = registrations.filter((r) => r.guardCount === 0);

  if (update) {
    const existing = new Map(readAllowlist().map((entry) => [routeKey(entry), entry]));
    const routes: PublicRouteEntry[] = unguarded
      .map((r) => {
        const previous = existing.get(routeKey(r));
        return {
          method: r.method.toUpperCase(),
          path: r.path,
          file: r.file,
          reason: previous?.reason ?? "UNREVIEWED — inherited when the audit was introduced",
        };
      })
      .sort((a, b) => routeKey(a).localeCompare(routeKey(b)));

    writeFileSync(
      ALLOWLIST_PATH,
      `${JSON.stringify(
        {
          description:
            "Routes registered with no middleware. A route may only appear here deliberately — " +
            "see server/lib/route-guard-audit.ts. Entries marked UNREVIEWED are a backlog, not an " +
            "approval: each needs a decision to be either guarded or given a real reason. " +
            "Regenerate with: npm run audit:routes -- --update",
          totalRoutes: registrations.length,
          unguardedRoutes: routes.length,
          unreviewed: routes.filter((r) => r.reason.startsWith("UNREVIEWED")).length,
          routes,
        },
        null,
        2,
      )}\n`,
    );
    console.log(
      `allowlist written: ${routes.length} unguarded of ${registrations.length} routes ` +
        `(${routes.filter((r) => r.reason.startsWith("UNREVIEWED")).length} unreviewed)`,
    );
    return;
  }

  const { undeclared, stale, passed } = auditRoutes(registrations, readAllowlist());

  if (stale.length > 0) {
    console.error(`\n${stale.length} allowlist entr(y/ies) no longer match a route:\n`);
    for (const entry of stale) console.error(`  ${routeKey(entry)}`);
    console.error("\nThe route was renamed, guarded or removed. Refresh the allowlist:");
    console.error("  npm run audit:routes -- --update");
  }

  if (undeclared.length > 0) {
    console.error(`\n${undeclared.length} route(s) registered with NO middleware:\n`);
    for (const route of undeclared) {
      console.error(`  ${route.method.toUpperCase()} ${route.path}`);
      console.error(`      ${route.file}:${route.line}`);
    }
    console.error(
      "\nAdd a guard. If the route is genuinely public, add it to config/public-routes.json " +
        "with a reason — that is a reviewable line in the diff, which is the point.",
    );
  }

  if (!passed) process.exit(1);

  const allowlist = readAllowlist();
  const unreviewed = allowlist.filter((r) => r.reason.startsWith("UNREVIEWED")).length;
  console.log(
    `route guard audit passed ✓ (${registrations.length} routes, ` +
      `${allowlist.length} allowlisted, ${unreviewed} still unreviewed)`,
  );
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main();
}
